repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v21.1.2" # Use the sha / tag you want to point at
    hooks:
      - id: clang-format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-format
