FROM ghcr.io/astral-sh/uv:alpine
WORKDIR /python-uvicorn

RUN apk add build-base \
  cairo-dev pango-dev python3-dev

COPY ./ ./
ENV UV_NO_DEV=1
RUN uv sync --locked

ENV PATH="/python-uvicorn/.venv/bin:$PATH"

ENTRYPOINT ["python-uvicorn"]
