# generated by zon2nix (https://github.com/jcollie/zon2nix)
{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:
let
  unpackZigArtifact =
    {
      name,
      artifact,
    }:
    runCommandLocal name
      {
        nativeBuildInputs = [ zig ];
      }
      ''
        hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
        mv "$TMPDIR/p/$hash" "$out"
        chmod 755 "$out"
      '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "#" url;
      url_base = builtins.elemAt parts 0;
      url_without_query = builtins.elemAt (lib.splitString "?" url_base) 0;
      rev_base = builtins.elemAt parts 1;
      rev =
        if builtins.match "^[a-fA-F0-9]{40}$" rev_base != null then rev_base else "refs/heads/${rev_base}";
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
      fetchSubmodules = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
    }:
    let
      parts = lib.splitString "://" url;
      proto = builtins.elemAt parts 0;
      path = builtins.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig {
          inherit name hash;
          url = "http://${path}";
        };
        "git+https" = fetchGitZig {
          inherit name hash;
          url = "https://${path}";
        };
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "N-V-__8AACUhPQDA5Mvi9LLrRdKvMv8hAerVBZWKQkfHSqn1";
    path = fetchZigArtifact {
      name = "algorithm";
      url = "git+https://github.com/boostorg/algorithm?ref=boost-1.89.0#32c5a6327cfdca5d41ce0f1d8849b811886daa2f";
      hash = "sha256-+rnClgwIlt25oJ0MVzjaJn3N7eD3QXi0rf0v+cZDgvw=";
    };
  }
  {
    name = "N-V-__8AALiaAQBkqXkWmZ90CMgy2wbe3pgedtfkFYCsLgto";
    path = fetchZigArtifact {
      name = "align";
      url = "git+https://github.com/boostorg/align?ref=boost-1.89.0#5ad7df63cd792fbdb801d600b93cad1a432f0151";
      hash = "sha256-pmYhhmJk69bAemvm2RNW9wSzUnaSMYNZz5QHZmRO7YY=";
    };
  }
  {
    name = "N-V-__8AAOQpAgDDYwqpKtDmaN6D3mnObQIVMFIYhyhhtsq_";
    path = fetchZigArtifact {
      name = "any";
      url = "git+https://github.com/boostorg/any?ref=boost-1.89.0#9b1941c787f2769fcb6afdb0cef621db80f953a6";
      hash = "sha256-BSDvDYphP60T8s3IdtOiA3iyQSz+W+E0QlsZReHtoG8=";
    };
  }
  {
    name = "N-V-__8AAFlMAgBlNIseNerkSVmUC9TxOlWrCI7SA6j_v4uz";
    path = fetchZigArtifact {
      name = "array";
      url = "git+https://github.com/boostorg/array?ref=boost-1.89.0#e988ef9c4a7d64be2850dc8de18b6461e094d4ae";
      hash = "sha256-P7pFHRtIkmDxWv3Oq5xul5l2eh2zX6rAr6/24pk/daY=";
    };
  }
  {
    name = "N-V-__8AAA446gD7kQ4vIk7qwv3fmTLLki4Og8IY9XPQ2Iit";
    path = fetchZigArtifact {
      name = "asio";
      url = "git+https://github.com/boostorg/asio?ref=boost-1.89.0#f529dbbd6156b57f079f1387768b585a37d0f621";
      hash = "sha256-+pAHrRdzO5gHElLaQCOu+lTqOVO7vfhzTPKmMw9zyPk=";
    };
  }
  {
    name = "N-V-__8AAJHfAQDwMmkntNc6N5YRCF2WsmHiaO9p1yJr6BJi";
    path = fetchZigArtifact {
      name = "assert";
      url = "git+https://github.com/boostorg/assert?ref=boost-1.89.0#5dcb2af5213ae132b7531e45e7f93258cc33ffd8";
      hash = "sha256-sBQQ8efXevprZVGNOVnyiNGcYDL72BWBQe5KqHCQ8+U=";
    };
  }
  {
    name = "N-V-__8AANlPGwDDXJm-H0ZZPDpBfm9RChfDqOnB-A9fDn_Y";
    path = fetchZigArtifact {
      name = "atomic";
      url = "git+https://github.com/boostorg/atomic?ref=boost-1.89.0#8a6de6d93dbe123134deff264851a18d96063764";
      hash = "sha256-3OjP8NRc6Y7tDbxUC0jupZPAY2+r1SL3nIoNaJP09FA=";
    };
  }
  {
    name = "N-V-__8AAJAkjwAYYXHVJKUhUMKuToV0TNmsBJD2iHWobxdT";
    path = fetchZigArtifact {
      name = "beast";
      url = "git+https://github.com/boostorg/beast?ref=boost-1.89.0#9b24b28d502946583300d3e58767cb30a8ec8486";
      hash = "sha256-G4Bjrh4ENn841dI8drOZDPhr9hMRTO+ySo9oXDNYxzU=";
    };
  }
  {
    name = "N-V-__8AAMckMACDAWQbKCN5wEWdCcnf7fLMkfYBB5wySXUB";
    path = fetchZigArtifact {
      name = "bimap";
      url = "git+https://github.com/boostorg/bimap?ref=boost-1.89.0#f64de6d045bf6aa3f39a672604bcccbc97291525";
      hash = "sha256-ZZn2oSdmSy8iygrZq3+RMOkSY0zVaODcgZbAN/w80Cc=";
    };
  }
  {
    name = "N-V-__8AAEqrCgDamRDkhpeo431rBpKsRdNmJVEJ4L3xaF1x";
    path = fetchZigArtifact {
      name = "bind";
      url = "git+https://github.com/boostorg/bind?ref=boost-1.89.0#a541a8d5c16920e1836d09299915890d687efe36";
      hash = "sha256-xdT8F7JuinEWbY5EOey21oUTjvF/7cPsu1tD31oEVus=";
    };
  }
  {
    name = "N-V-__8AAOPNBgANRzjmP1uiGRpxTpUnUwFR3c3PZVUAMP40";
    path = fetchZigArtifact {
      name = "bloom";
      url = "git+https://github.com/boostorg/bloom?ref=boost-1.89.0#42ac5003f8742981a9731ae443a99be6b8fa23bc";
      hash = "sha256-stdMQPcC0ejfAtak5bQyOtKJRjsz8597+Cy1kXKkZJ8=";
    };
  }
  {
    name = "boost_libraries-1.89.0-frkKHLCXAQASDNJkyAQCiQZKs1kmnLozkP6Mx46J5d1_";
    path = fetchZigArtifact {
      name = "boost";
      url = "git+https://github.com/allyourcodebase/boost-libraries-zig#b04c323025691d45ad8e1530c0b523e765a9f643";
      hash = "sha256-sQVCFXs0cQ5NA/wukkMv6tbrbpjdmMMldbtq9o2ieHk=";
    };
  }
  {
    name = "N-V-__8AAMa4BwCpVigub7aSIEgUJohLziOJXDmB3igMP7M8";
    path = fetchZigArtifact {
      name = "callable_traits";
      url = "git+https://github.com/boostorg/callable_traits?ref=boost-1.89.0#2a56a3a2496cdb66496f844db55085dd992d5e49";
      hash = "sha256-XbO+SB5QhKAJigL/SBl9OIIQl49u6pUuqAMguU8SftQ=";
    };
  }
  {
    name = "N-V-__8AAJmKFwBGnXY8Tntsqzf7D8ZUV1gzARlvkEIG-mzN";
    path = fetchZigArtifact {
      name = "charconv";
      url = "git+https://github.com/boostorg/charconv?ref=boost-1.89.0#728f7c4a85d7893c91c5fd85220367bb17cd06b5";
      hash = "sha256-/2gydYQoeCVqoy21f4hgUZ6YqgSVDuyEW8qKyYJrN0M=";
    };
  }
  {
    name = "N-V-__8AAHKoEgC2FVY0dM8korgUTF2zl2VwWnrFCaE5RHS8";
    path = fetchZigArtifact {
      name = "chrono";
      url = "git+https://github.com/boostorg/chrono?ref=boost-1.89.0#ef510872039483dc66b7b2263c43c273a9aaecd6";
      hash = "sha256-AK5kbnidHvzGpUd/VU4RPrsJsbQ2rB8obyJOa4ZrWMc=";
    };
  }
  {
    name = "N-V-__8AAP87CACoPesrgVNchRs4kD-neM6sb9cTaXhniOPo";
    path = fetchZigArtifact {
      name = "circular_buffer";
      url = "git+https://github.com/boostorg/circular_buffer?ref=boost-1.89.0#a08a5b55ee82e0c2487523471379ac53a23935dc";
      hash = "sha256-t5fSfuQFGNb1cQUkcdxu4i8FbEQAfddhtYAEen6bCGE=";
    };
  }
  {
    name = "N-V-__8AABq_DgC0lnu8by8GZoGFe0a6uusmJuZ8U3WU_g0r";
    path = fetchZigArtifact {
      name = "cobalt";
      url = "git+https://github.com/boostorg/cobalt?ref=boost-1.89.0#57181cacc5b8d5079d95a33b7aa078d0f5f16147";
      hash = "sha256-iLRwuZ9aWKewDwhrTyDw1ZLcwy43fpbtf4Nevxs3zZ0=";
    };
  }
  {
    name = "N-V-__8AAJXCBgA7KCqx4FXdE85HRUeu8t97czaLcbgr1HbL";
    path = fetchZigArtifact {
      name = "compat";
      url = "git+https://github.com/boostorg/compat?ref=boost-1.89.0#e3746402659838fbd5efd91f4110ad0e0c63c957";
      hash = "sha256-kDUftNaOE2Zcjo9LQDCdsjuwuctLpFxW9iwC1KPtRf0=";
    };
  }
  {
    name = "zig_compile_commands-0.0.1-OZg5-ULBAABTh3NXO3WXoSUX1474ez0EouuoT2yDANhz";
    path = fetchZigArtifact {
      name = "compile_commands";
      url = "https://github.com/the-argus/zig-compile-commands/archive/70fb439897e12cae896c071717d7c9c382918689.tar.gz";
      hash = "sha256-oKp+UyF31qNyx7ctIs6ShOQsdDowMJSiedUpKHH+Pt0=";
    };
  }
  {
    name = "N-V-__8AAL2PJwA7essATOp2Xd8l1jEo8e7fyahbreh2v3mQ";
    path = fetchZigArtifact {
      name = "compute";
      url = "git+https://github.com/boostorg/compute?ref=boost-1.89.0#cf7907574d6159cd43e6cf687a7b656278c61dd0";
      hash = "sha256-OwoB+PLiDp5QdKy77qDFfBMJ6e8WzLjAC8OBWTiIB+Q=";
    };
  }
  {
    name = "N-V-__8AAKR6BADavdkISDKa2l67WkyvTn1krdMceO6evWjs";
    path = fetchZigArtifact {
      name = "concept_check";
      url = "git+https://github.com/boostorg/concept_check?ref=boost-1.89.0#0ef7f2b5daeaa125a53d98affba8f40091d24b17";
      hash = "sha256-nsf7frCia0fgBpfimW+IqznnVfMSmar9KEKB5sccPPI=";
    };
  }
  {
    name = "N-V-__8AAGThJwBWc_L1fi6RFm_jHgif_MY2haphDzC03gJK";
    path = fetchZigArtifact {
      name = "config";
      url = "git+https://github.com/boostorg/config?ref=boost-1.89.0#bf8c8bd7960cd8505210838f86bd28fb4fb71071";
      hash = "sha256-aPvWkk6F0boHvhQsNRn/Dafkvq5CUuL+xW4diiG/HWU=";
    };
  }
  {
    name = "N-V-__8AAC1wSgBqFydUHgmzFQVVdXrHxrJoLKCBMqkxZ9L9";
    path = fetchZigArtifact {
      name = "container";
      url = "git+https://github.com/boostorg/container?ref=boost-1.89.0#e8baf848bc426022dffbc814db8e1261d6033d4b";
      hash = "sha256-i2eaT1vx2xgmqXw2sEXJH9Mmo+QLy8NNTHUsAfKKyYc=";
    };
  }
  {
    name = "N-V-__8AAJ2DBQCKC9z4NhZswoPXswGEttik3uBYBck-CZ2V";
    path = fetchZigArtifact {
      name = "container_hash";
      url = "git+https://github.com/boostorg/container_hash?ref=boost-1.89.0#5d8b8ac2b9d9d7cb3818f88fd7e6372e5f072ff5";
      hash = "sha256-lKxh8nwQSIFX+lFAWJlUmUwxt2xM9678PFbkolkg2SE=";
    };
  }
  {
    name = "N-V-__8AAFsNGgB3V1msMNp3dMgDlxSplQS2LANIzqhi3OvZ";
    path = fetchZigArtifact {
      name = "context";
      url = "git+https://github.com/boostorg/context?ref=boost-1.89.0#3af0091efa65892e030add013417840f80b13e08";
      hash = "sha256-f8+ECYXwDBF9/cyLdsuqeGe7LVycj6shHyAhhhl8uYQ=";
    };
  }
  {
    name = "N-V-__8AAF_HAAAa2M3jMn8cCdW6jOG3mNdWlDp6AFotkaIL";
    path = fetchZigArtifact {
      name = "conversion";
      url = "git+https://github.com/boostorg/conversion?ref=boost-1.89.0#b74a4c34cb181a8a26d35d05fab608426449626a";
      hash = "sha256-95L3qltl5redVxlqe7oYcWUsDlpN6U2lZdi2YJpTgnQ=";
    };
  }
  {
    name = "N-V-__8AADOWEAAMuUSjDb6dpGa4US3dPfF2z4QecdQrOusY";
    path = fetchZigArtifact {
      name = "core";
      url = "git+https://github.com/boostorg/core?ref=boost-1.89.0#a128501403c08d70475cc87c4e511b59744b1aa1";
      hash = "sha256-VMu7/fPXlGWxkasp7MmBEW/Jya6nUpGjZbp3KYUZ/5U=";
    };
  }
  {
    name = "N-V-__8AADeWBACdc4-qLylEme_d0C7JkljJh5TukDftAjNI";
    path = fetchZigArtifact {
      name = "coroutine2";
      url = "git+https://github.com/boostorg/coroutine2?ref=boost-1.89.0#dbbf042e0a9081b4119d491b788ae0fe7c03192a";
      hash = "sha256-MSOtRWoByGod3i49owJApiCjw9pu165OqIp4bSis6Vs=";
    };
  }
  {
    name = "N-V-__8AAEjTAwB6uQ-nvXSJyu_Gzsk-5lgG4fcJ_-4mfaZV";
    path = fetchZigArtifact {
      name = "crc";
      url = "git+https://github.com/boostorg/crc?ref=boost-1.89.0#75146a958410c789381a4609166c754d35548e2d";
      hash = "sha256-lmVm65cHe43RoidOJJ2g13I3SJAf4Lmg2skcRq41zYE=";
    };
  }
  {
    name = "N-V-__8AAMOOGwBP_hCvwzKYcwNojW9urbnpDTOB9e7CFFTD";
    path = fetchZigArtifact {
      name = "date_time";
      url = "git+https://github.com/boostorg/date_time?ref=boost-1.89.0#85e637cb325208c2af9af791c3a1948b4888c6cd";
      hash = "sha256-I1Oo/3MyHnsBSEjQ7OieCVn3B0ImSYDaPqoMMW0kPjg=";
    };
  }
  {
    name = "N-V-__8AADr6AwBPtdKdJXDzLN24sfh_A-Ln0CEymC5BGrfo";
    path = fetchZigArtifact {
      name = "describe";
      url = "git+https://github.com/boostorg/describe?ref=boost-1.89.0#b64177c39f929998e3a145992d0328712e095c29";
      hash = "sha256-nZohSKFU6tQfBQa8GTd0jLe1qgqFoJlMUaISrmPP4Ng=";
    };
  }
  {
    name = "N-V-__8AABqQAwBjPZPQUVcSVlq2U4qbpVlTcMmpHvPCzzdu";
    path = fetchZigArtifact {
      name = "detail";
      url = "git+https://github.com/boostorg/detail?ref=boost-1.89.0#43238b75cee1a010d6ef6dc48dfc21c365d3796f";
      hash = "sha256-CNJh3zHJQdlmJUTkRxZ/QF14aLsrKivrRF1u7s927FY=";
    };
  }
  {
    name = "N-V-__8AAHUVBwBno0N-AuY5GL3NvDJCBDlWTIVae25QBzSE";
    path = fetchZigArtifact {
      name = "dll";
      url = "git+https://github.com/boostorg/dll?ref=boost-1.89.0#4105c3a8f8d5287b59b0185c45d4c9a768d92a55";
      hash = "sha256-nluvzCwxFDsM/sueovqxL23KCKXw8jnSRocYMKn7gZw=";
    };
  }
  {
    name = "N-V-__8AAE3GCACIRxAD3oWteML3w5sBwmm_njj5DG6cwX-Z";
    path = fetchZigArtifact {
      name = "endian";
      url = "git+https://github.com/boostorg/endian?ref=boost-1.89.0#c0b5c80603b8de7eeea8724c9a4f2761c3df06f2";
      hash = "sha256-fpG5BghLPZAKJuDqFHHaYjWrQ5bXveQMMQv/oFlhjbA=";
    };
  }
  {
    name = "N-V-__8AAI_2DwAAb7VpZLRfaT0nhgf4YaCGGSdiYOL9B7Ch";
    path = fetchZigArtifact {
      name = "exception";
      url = "git+https://github.com/boostorg/exception?ref=boost-1.89.0#9238ef8e7f97e619ed3e58bc7becf16b4966ccf0";
      hash = "sha256-oziBPE66j9nntT4eLj3lh8+xL3hjWu0B4UGhjuUoqI8=";
    };
  }
  {
    name = "N-V-__8AAAYbSABEngHJeWbJCaDFDOxpNEIStZP1Bm5i6LR5";
    path = fetchZigArtifact {
      name = "fiber";
      url = "git+https://github.com/boostorg/fiber?ref=boost-1.89.0#238487b543e8863c647d31a82ccfc3fa11a960d9";
      hash = "sha256-JpyVVA2528nfCsYSl0r58E6uw+V7OrXSHb3UBwLRoE8=";
    };
  }
  {
    name = "N-V-__8AADN2FwCbU_54Zgoc765ecy_CfPCwIlBhh628Dg0A";
    path = fetchZigArtifact {
      name = "filesystem";
      url = "git+https://github.com/boostorg/filesystem?ref=boost-1.89.0#d316a9d3aa09bb3d200646cc587a16e3b9be5f39";
      hash = "sha256-knhjAm7vz2gEIpIX7uxboIqIy6/2O/tXsxXD8uwR6yI=";
    };
  }
  {
    name = "N-V-__8AAGu-BABbjN6CgUc_0vHRqCMd3v7bNbI_zPUWZimO";
    path = fetchZigArtifact {
      name = "format";
      url = "git+https://github.com/boostorg/format?ref=boost-1.89.0#66075102416bc5d0f8e0bd151a19013dadbf94ce";
      hash = "sha256-S46TJZNFw3sDw8D5Sa6zVTt5dkfvjGahLHJ5OC5dHXs=";
    };
  }
  {
    name = "N-V-__8AAO2HBAC1TXKtzo65bNT9u1fcVPWy8hJ5bu3NbgbN";
    path = fetchZigArtifact {
      name = "function";
      url = "git+https://github.com/boostorg/function?ref=boost-1.89.0#f6b538dbed2e3047dcbd09eb3f5c7f1ffa90d0a9";
      hash = "sha256-ZfEd50J1Lq1W2X90QYLgkudvofmNHlwgVmIgpQWqdtE=";
    };
  }
  {
    name = "N-V-__8AAIKQDwA0c--Aj6OaH4orOc17CDZKowBOpZoVO1YG";
    path = fetchZigArtifact {
      name = "function_types";
      url = "git+https://github.com/boostorg/function_types?ref=boost-1.89.0#6fba35ace59e9e7b1c3007ca6246a42ed6ead145";
      hash = "sha256-GOyxfIPqyCTHm7Snm0UcTHQaR8bNA5QlNbX+0J1fwSI=";
    };
  }
  {
    name = "N-V-__8AAHz5BAAHbQ1m2VR4nU0pzxbDjelQBNnSmWDxZvAp";
    path = fetchZigArtifact {
      name = "functional";
      url = "git+https://github.com/boostorg/functional?ref=boost-1.89.0#6a573e4b8333ee63ee62ce95558c3667348db233";
      hash = "sha256-U2tk/oxz+TTO/8Cz0ruSnG9QqjXBXAXLaXiedIuzQLI=";
    };
  }
  {
    name = "N-V-__8AAOQD7wC4pEgByUp4TphJvvtm476CD8o8BM14q_T4";
    path = fetchZigArtifact {
      name = "fusion";
      url = "git+https://github.com/boostorg/fusion?ref=boost-1.89.0#53da4e0b2c8cd4969b09fa646d314ac0c414c1ff";
      hash = "sha256-oTJ2laEBpjx3MMS9QKFg9aW6LlfLH7JWcx9LABBmrgI=";
    };
  }
  {
    name = "N-V-__8AAE6TewG5DeroUp9WPc2kWZPN9Nlb1CcbAhUYNtrp";
    path = fetchZigArtifact {
      name = "geometry";
      url = "git+https://github.com/boostorg/geometry?ref=boost-1.89.0#617d75e0cda78b1f05590319200973514b609097";
      hash = "sha256-7uUDfD8snoyatiA6YKF/i8cpyRfiST2ZwlmKiF6B25A=";
    };
  }
  {
    name = "N-V-__8AAIbhogBBR0oCd8YkyM92CNRHRssIwCegr2aH_KJ0";
    path = fetchZigArtifact {
      name = "gil";
      url = "git+https://github.com/boostorg/gil?ref=boost-1.89.0#201f31c76eed54b304f8d89e44da08a5e8825094";
      hash = "sha256-kpSFVBEjAmTB1p06tXO8gVc28SxDR9aw8QapQbBhscU=";
    };
  }
  {
    name = "N-V-__8AAPedBgE6M27iCELCBd3vV5OJ8UgeUojSrHfGLLEV";
    path = fetchZigArtifact {
      name = "graph";
      url = "git+https://github.com/boostorg/graph?ref=boost-1.89.0#54a94911e68dccf5812b32d018566566700499f3";
      hash = "sha256-djo7DIA49MXStNzp9fJPyBj+L1nuTVu6Z5Sf1Cf2ZtY=";
    };
  }
  {
    name = "N-V-__8AAIg9TQDdQ2vR5IvCCy4llIYMiArhZrT6i7glL-oz";
    path = fetchZigArtifact {
      name = "hana";
      url = "git+https://github.com/boostorg/hana?ref=boost-1.89.0#bc49ee25638e59d977edff5737b4e6bf12c1e5ea";
      hash = "sha256-lFaH6qPEDtYEKAjZhFyvqtfQR3GENkE/15zkGNgAy7A=";
    };
  }
  {
    name = "N-V-__8AANSEDwB5vng_bAG7nvSDqM_lbRkAt6N4sbRHmGrW";
    path = fetchZigArtifact {
      name = "hash2";
      url = "git+https://github.com/boostorg/hash2?ref=boost-1.89.0#5cf695e5e2466df247561894b3c15b4394a68486";
      hash = "sha256-7WvV9zbMApgBlcefO13tF1P0UJ3RRZj+Dmr9T9j7KqI=";
    };
  }
  {
    name = "N-V-__8AAIGIBQBhI_4SU_mzopfWYmnFFYtDC2YjSCMA3NrO";
    path = fetchZigArtifact {
      name = "heap";
      url = "git+https://github.com/boostorg/heap?ref=boost-1.89.0#7db5d9db6615b40239a8bb9383a12bd56924bd07";
      hash = "sha256-q0vQ89rJaAY/SGN5cqe/4hvY6YWZc2pXaBPCQIzoc2E=";
    };
  }
  {
    name = "N-V-__8AALKyCwA3vPUL9O__Q4y3m193L6sycgS9J03KBzsm";
    path = fetchZigArtifact {
      name = "hof";
      url = "git+https://github.com/boostorg/hof?ref=boost-1.89.0#63ac019fca325038bfb4f56db17fbb281d2b5f49";
      hash = "sha256-KWRf8rfn8pPZsuXWTPkv2rhkAF0RqjxN8OMZL9Hy0/g=";
    };
  }
  {
    name = "N-V-__8AACeoAwDBhzf1Wp8HsLSDiKoijtb2R2i0X_0mVcCh";
    path = fetchZigArtifact {
      name = "integer";
      url = "git+https://github.com/boostorg/integer?ref=boost-1.89.0#0fefe9831abf014d3a7da7172755aae0f54e85f0";
      hash = "sha256-lr90bVhBJIWjYAVTPLrqZI8NpQQnRbWTmJ9sS+yJvbI=";
    };
  }
  {
    name = "N-V-__8AAK3NKABu1nbMdl-FFUCozuoyor6g7sC_9ZFBQy9P";
    path = fetchZigArtifact {
      name = "interprocess";
      url = "git+https://github.com/boostorg/interprocess?ref=boost-1.89.0#2c3d4f8bb91400298f285ebd197d808cf14b126a";
      hash = "sha256-nZChnwvQ5e1V5bQKClwuObAuHOOor5pE5EDmdVzugyY=";
    };
  }
  {
    name = "N-V-__8AAI5fBgALNeyXb0DEVCArdX3aMz4rwz4bZhiQ8Pn4";
    path = fetchZigArtifact {
      name = "interval";
      url = "git+https://github.com/boostorg/interval?ref=boost-1.89.0#565d0d754f851eb9447745b359ca5be6a033918c";
      hash = "sha256-Bgh6+BEgsjRc5eiDpGmEpJAyMBf+DpoiCh2xAzQRlBg=";
    };
  }
  {
    name = "N-V-__8AAMDrIwAmho_WzB-7Tt4V7NqUcCSwj0Oda5mjoPWd";
    path = fetchZigArtifact {
      name = "intrusive";
      url = "git+https://github.com/boostorg/intrusive?ref=boost-1.89.0#23e7a9cbf54f69f2bdc22951af959af74b037d10";
      hash = "sha256-PmMRJH3nDe3umDPH8gHe3se1xryk8buMqnIO+1VYuzg=";
    };
  }
  {
    name = "N-V-__8AAFuJAQDT6Xjpc49iuweYnJ4j4UM3h134E7SjgK2W";
    path = fetchZigArtifact {
      name = "io";
      url = "git+https://github.com/boostorg/io?ref=boost-1.89.0#342e4c6d10d586058818daa84201a2d301357a53";
      hash = "sha256-7O2qCHTybyhzqkJUftJ/7W06EhAOzKbX5ulYh5d0Es8=";
    };
  }
  {
    name = "N-V-__8AADTThQCR3QabRhSONgDag-0YZ2ZhtCvqZnTdmael";
    path = fetchZigArtifact {
      name = "iostreams";
      url = "git+https://github.com/boostorg/iostreams?ref=boost-1.89.0#8561bdb8bcd0a1b528d60c090407233b0c1d9148";
      hash = "sha256-06nyC2gTshoIj4DFy0SPdND0FyKmhdYxjlRAdFJ15Ug=";
    };
  }
  {
    name = "N-V-__8AAJzPLAAX-jXQUFcp9UoyW-ROazUE4O0rfmkev7SZ";
    path = fetchZigArtifact {
      name = "iterator";
      url = "git+https://github.com/boostorg/iterator?ref=boost-1.89.0#2a0b753691f326154436fa641287e6336c19d80e";
      hash = "sha256-ljEisWLtU3EFZAHZXZSr7DgqPzC2o81AP0/p1H7BG/o=";
    };
  }
  {
    name = "N-V-__8AAKdJLQG_Htvv2JMcB2rMck3xsHsXXykRgsThNc5r";
    path = fetchZigArtifact {
      name = "json";
      url = "git+https://github.com/boostorg/json?ref=boost-1.89.0#3c80c097d2fe2266d3d41f4121d7af24e122e996";
      hash = "sha256-kPWXw928GPY3MlVYuQ3uO3FYPeMq9Qq6l337SmNv2zU=";
    };
  }
  {
    name = "N-V-__8AAC21DwAnTqvk8h56Tf6exNRnueYJ3qdnHCAGu8PJ";
    path = fetchZigArtifact {
      name = "leaf";
      url = "git+https://github.com/boostorg/leaf?ref=boost-1.89.0#aff38b5be343ac6f1588e3258d126224e5347934";
      hash = "sha256-/6LlkfWzYPWANpCKwlbLzjBzExBwg3wBMIcpFYRvODc=";
    };
  }
  {
    name = "N-V-__8AANFqBQDwAVbaLgTb6OO5ZzQLBjMdd1Ysm06CTj2V";
    path = fetchZigArtifact {
      name = "lexical_cast";
      url = "git+https://github.com/boostorg/lexical_cast?ref=boost-1.89.0#5326b49475f27d04e07fda8759211b5d65d07f64";
      hash = "sha256-EVw+1e43ZAA8J2QUHkwkR5Z3pUCKnMZkxKBs5XltRbo=";
    };
  }
  {
    name = "N-V-__8AAHGaFQDt5k8TphnVwa6vACn9SjMFY-sjx1bHeyhn";
    path = fetchZigArtifact {
      name = "local_function";
      url = "git+https://github.com/boostorg/local_function?ref=boost-1.89.0#258aeaa6c1a9618c02ca4e4af2890e70833035f0";
      hash = "sha256-LlbxpEQCUkPKlCg10mJGtD6BEa6s2wUInj16UXXmUtA=";
    };
  }
  {
    name = "N-V-__8AAIV1FwDSpq88-9u5tgH11coxur4KVuaAT4qc_NMJ";
    path = fetchZigArtifact {
      name = "locale";
      url = "git+https://github.com/boostorg/locale?ref=boost-1.89.0#9b7775715a50e62c5bc0ed99d65e0f56c06361f4";
      hash = "sha256-zAMYVfR1CL5mCgTYV9ujW0Fl+8tVndX/OK/ZVJImdQo=";
    };
  }
  {
    name = "N-V-__8AAI7OAwBNGHbb3auG83WXxmwyZQOteVESKIeCqVQ3";
    path = fetchZigArtifact {
      name = "lockfree";
      url = "git+https://github.com/boostorg/lockfree?ref=boost-1.89.0#4a69f38b3d1d20ac56e60095a550ffb2ce4ccbd7";
      hash = "sha256-wOXDFx0XxlAm9/CRilQiUe+E5pbVF6c9NBIswdGQb1o=";
    };
  }
  {
    name = "N-V-__8AADlcNQDhH366SuEkCxtTVAsvndumYUvXxtSEcoKu";
    path = fetchZigArtifact {
      name = "log";
      url = "git+https://github.com/boostorg/log?ref=boost-1.89.0#ad2eb6c4e54ebefb667fac25672bdd723fe55f37";
      hash = "sha256-lLeNpaFDnv6SzEUnZj8RC2PkbbZVVryfkWeE82GoYgI=";
    };
  }
  {
    name = "N-V-__8AADyLAQB5o2e2wLaIFkmW8NQ9NAo0Se1kEokyRggG";
    path = fetchZigArtifact {
      name = "logic";
      url = "git+https://github.com/boostorg/logic?ref=boost-1.89.0#9b8703a2d6623405323b892f1d126a6b17ca1651";
      hash = "sha256-GUoHIzTeYn0eL4gN9qjFSJu9nnl8dLT2PGvc7w1egg8=";
    };
  }
  {
    name = "N-V-__8AADz7RAYjVkkNadLVj35VD5OjXs7r2N1RR6Cdjxab";
    path = fetchZigArtifact {
      name = "math";
      url = "git+https://github.com/boostorg/math?ref=boost-1.89.0#5e088ffe2ed0e237b9069e3a7352865283d8f196";
      hash = "sha256-hrpMduFTOu9xqajj6duHVNieWOHDu3Zl2uZbYBTKCSA=";
    };
  }
  {
    name = "N-V-__8AADVmDABcDKw_D3-FlptU7zo0958BFPZBvuRT0d9E";
    path = fetchZigArtifact {
      name = "move";
      url = "git+https://github.com/boostorg/move?ref=boost-1.89.0#40d2be68bae9acfb4f165cdaab0a4246c5af5485";
      hash = "sha256-eXS9ooLEzzItTcfTH0lzoyjDykr+dCGzJcTj/v9V8k4=";
    };
  }
  {
    name = "N-V-__8AAOwSDwDMj4wdHAD_UtIddVzzdKrSuVY4bhAngr4e";
    path = fetchZigArtifact {
      name = "mp11";
      url = "git+https://github.com/boostorg/mp11?ref=boost-1.89.0#2fb81c24534663a99f9570b99a3c748393a23dba";
      hash = "sha256-HcQJ/PXBQdWVjGZy28X2LxVRfjV2nkeLTusNjT9ssXI=";
    };
  }
  {
    name = "N-V-__8AABpViQDRvjP80WTO508uOFMp2xkI5xzYFM2lK-I4";
    path = fetchZigArtifact {
      name = "mpl";
      url = "git+https://github.com/boostorg/mpl?ref=boost-1.89.0#74d927f9847c60b908beac94e1198d1985380abf";
      hash = "sha256-UvgPOuVibz9GEpzDOOGgTvSunYDvErQfqsb9xvj+xic=";
    };
  }
  {
    name = "N-V-__8AAP4lDgBa2x-KENz-ob8HIYVLP3Q637QSoAEf6KJ5";
    path = fetchZigArtifact {
      name = "mqtt5";
      url = "git+https://github.com/boostorg/mqtt5?ref=boost-1.89.0#620df1f9934925ac6044e4619c701d6dcf9dc8b6";
      hash = "sha256-DuEpqLS5ROD7aiwXHU3RKttgEnSXFe9VkC1DSt6il/4=";
    };
  }
  {
    name = "N-V-__8AAFycUwBUUnF2yUTADUwmx3-NW3GtNEQFb7wBzgIv";
    path = fetchZigArtifact {
      name = "msm";
      url = "git+https://github.com/boostorg/msm?ref=boost-1.89.0#33e77cbfc70956d4b99f3dfc9c1e83848fe2550b";
      hash = "sha256-18lw2/ob5HIXfBInG32NhdnbHKE3tvGilvhb2QelHv8=";
    };
  }
  {
    name = "N-V-__8AALTJBwCHHiM6Be55w4Df-SLIOyD0xzirjjR8PIBN";
    path = fetchZigArtifact {
      name = "multi_array";
      url = "git+https://github.com/boostorg/multi_array?ref=boost-1.89.0#0c5348bef71b890c4bd06eff1ee5ebda69e7b27a";
      hash = "sha256-oG70CtBohtcka45hXehFHlpoThZiYlbKJtDtkB1p0O4=";
    };
  }
  {
    name = "N-V-__8AANNsIwDsiqCKw5nWGO_Y7tJpXDYvrWeMWnGtwjAf";
    path = fetchZigArtifact {
      name = "multi_index";
      url = "git+https://github.com/boostorg/multi_index?ref=boost-1.89.0#3a4ddd9c7ad29032edd6086687136c42d0dfb03f";
      hash = "sha256-DoLjlX6/SlMaoahtriwjeARHxMTx4uS68wBVRPw6JZU=";
    };
  }
  {
    name = "N-V-__8AAPno2wCeM0mFzPP8Bip9rmLRU8piEhhGB31f5VJk";
    path = fetchZigArtifact {
      name = "multiprecision";
      url = "git+https://github.com/boostorg/multiprecision?ref=boost-1.89.0#e0c112538ff1e903594d039f2eb97e0057737e5d";
      hash = "sha256-IQQt/4MZfqSU32UAQDPxN1rfuUDAyIMTGp8WjKqmpkk=";
    };
  }
  {
    name = "N-V-__8AAOCdTABust-DtGP27othQo0yvXts6oXGQHdi4HNr";
    path = fetchZigArtifact {
      name = "mysql";
      url = "git+https://github.com/boostorg/mysql?ref=boost-1.89.0#6a82609638e88bcea2985069dfc356f32a575a55";
      hash = "sha256-GBegkDfMMlM58bo8Oc3MiU33fH4JEdk/YVPzc1qZt2o=";
    };
  }
  {
    name = "N-V-__8AAHx_BwCNYH9hpUM0OlDZWkGXywYtZ0of3GeRYvci";
    path = fetchZigArtifact {
      name = "nowide";
      url = "git+https://github.com/boostorg/nowide?ref=boost-1.89.0#b2f5f57fdb38ca42bc33b55d5e9cd7024e355399";
      hash = "sha256-wiK0l1clnja6eJSQPXiMXVNLMPa5xtbC5PNN7W6RjuE=";
    };
  }
  {
    name = "N-V-__8AACHiCQC1YZI5LZX4OT7n2FGUQSB9SSMSOUX1LMIn";
    path = fetchZigArtifact {
      name = "numeric_conversion";
      url = "git+https://github.com/boostorg/numeric_conversion?ref=boost-1.89.0#d1b479f7a4aa54d8ffb93d8dc4ee0c24670210d8";
      hash = "sha256-u9v7e7yLKsfiV8Btz4+hKNR9eI7BTFK7AWte8oGvreg=";
    };
  }
  {
    name = "N-V-__8AACbVJAB945DbAOb-qVUoGDlIZDUl75YagkF5R5jA";
    path = fetchZigArtifact {
      name = "odeint";
      url = "git+https://github.com/boostorg/odeint?ref=boost-1.89.0#9e75be5d9e435739b086aee928736fc241e77a4a";
      hash = "sha256-bidGeOEtd2+AVZ4Si7Zje3LiLvSLQLq29bYbW/NolOk=";
    };
  }
  {
    name = "N-V-__8AAAbXBgD7zMewPCjTL30k9q0XSXKrn4v2UoiKLByB";
    path = fetchZigArtifact {
      name = "optional";
      url = "git+https://github.com/boostorg/optional?ref=boost-1.89.0#121f3efde91de78ca018019904732f55d33b5788";
      hash = "sha256-RRHnzA5K/8NTC/gghxX0bWE2+MyZfAWWFOaZDyfcAns=";
    };
  }
  {
    name = "N-V-__8AACBiRQA64_Vr35VyzPDnQ7Dr1W7A1ANPoHYMRe1W";
    path = fetchZigArtifact {
      name = "outcome";
      url = "git+https://github.com/boostorg/outcome?ref=boost-1.89.0#9fab401aa0ee4e578ec6757c082b6f66c67a55c7";
      hash = "sha256-Zky1TYJqq/wfeDaaYAxzjnl454R0+y+GfRwsVj+Ys80=";
    };
  }
  {
    name = "N-V-__8AAL7NHACmKrgvrDf_7aXv_vsiixCWvOv2LHOh4JNk";
    path = fetchZigArtifact {
      name = "parameter";
      url = "git+https://github.com/boostorg/parameter?ref=boost-1.89.0#67861ef6ade2db396af4a3fd9e47647d8b01f73c";
      hash = "sha256-WSExKYojn5swQ1Zxuwggav+LfwC10kwpMdpkeDEpD18=";
    };
  }
  {
    name = "N-V-__8AAGCELwBEBL5NQiILNJoVf81b7n1hP0XgDA0wezX2";
    path = fetchZigArtifact {
      name = "parser";
      url = "git+https://github.com/boostorg/parser?ref=boost-1.89.0#c674e94c3d409b6ab0ee05429361e8b50fe30320";
      hash = "sha256-KIU54qfBmAPy/38+z+kjjlb4xNAJNNGluDMgFLxAFkI=";
    };
  }
  {
    name = "N-V-__8AAA72FQD6Y5k_wYXL6pRzLLVEF8mk_gxK99GmDtDK";
    path = fetchZigArtifact {
      name = "pfr";
      url = "git+https://github.com/boostorg/pfr?ref=boost-1.89.0#5034bf55fb6bd1efa7a14955bbb7171c2b3491fc";
      hash = "sha256-SaY3NHQSgSo7l8ZdZs35cvucdgMJHoqese8OV/+n8gk=";
    };
  }
  {
    name = "N-V-__8AALCYJwGwrs7rO_IvByy6Lt9m7O9-bYLL5JxbWw6M";
    path = fetchZigArtifact {
      name = "phoenix";
      url = "git+https://github.com/boostorg/phoenix?ref=boost-1.89.0#8913607a3788cb82d48ed461ea59c919b7bad3df";
      hash = "sha256-szO8RfKawPe1XhjRdWpHm9nii8dglpFQKlnQUGSwa4o=";
    };
  }
  {
    name = "N-V-__8AAAieLgDl61ANGt1eaCLj0oYtzF3PZ5Wzzr-1bD3s";
    path = fetchZigArtifact {
      name = "pool";
      url = "git+https://github.com/boostorg/pool?ref=boost-1.89.0#740c8076f9d02f0216e8f3dbb15d2fd80f67d7f4";
      hash = "sha256-JurFimHIzn1P4VHnyiHdCusHKuBINyn019bLXpBbN/M=";
    };
  }
  {
    name = "N-V-__8AAM3hCgB8Arslq5pHATUljnwANJKh9EMM95ERNJmK";
    path = fetchZigArtifact {
      name = "predef";
      url = "git+https://github.com/boostorg/predef?ref=boost-1.89.0#e1211a4ca467bb6512e99025772ca25afa8d6159";
      hash = "sha256-C1aMk1RkLMqSBIv8oTlfkZhlp1kzWqXoAn3Cyev9Jtc=";
    };
  }
  {
    name = "N-V-__8AALI0tQDZW9UfY8zpFBacRQKLZ19tOAZCL4OAlZtG";
    path = fetchZigArtifact {
      name = "preprocessor";
      url = "git+https://github.com/boostorg/preprocessor?ref=boost-1.89.0#cd1b1bd03900b68505822cfa25cb16851bd6caf1";
      hash = "sha256-4GTIVg58rx21Sqpj5fQH8VXVdHCGI9reauZ64ZlDhfA=";
    };
  }
  {
    name = "N-V-__8AANBKFAAlncl9PmGon5xIp81-MPLLC5nqH3aCeU6W";
    path = fetchZigArtifact {
      name = "process";
      url = "git+https://github.com/boostorg/process?ref=boost-1.89.0#5597aa0055b81017f6ea24cb652f07a014b12771";
      hash = "sha256-3YCG9PotrEBkXAEvrwAVyHBZDrNtPsTK12nY2pq4biw=";
    };
  }
  {
    name = "N-V-__8AAD5JAwBeVXAdgiQK80Ee_0gbp4P0gCNJ3s9rpU1a";
    path = fetchZigArtifact {
      name = "property_map";
      url = "git+https://github.com/boostorg/property_map?ref=boost-1.89.0#830cb6bce0b54fc1b2d7806901c1b8c8716964b7";
      hash = "sha256-sdI/2biFn2yVAE8h0REyUYnMttfllLcQc7OUBPqk5Qk=";
    };
  }
  {
    name = "N-V-__8AAGkzAQAB_B7Hu8v4b6LLy_b17j8t4kcFfZznwv51";
    path = fetchZigArtifact {
      name = "property_map_parallel";
      url = "git+https://github.com/boostorg/property_map_parallel?ref=boost-1.89.0#a2f90e9660e4e7e012c0b54a1338d8e69fb71906";
      hash = "sha256-GjmbkLEk4G+Gj+NhkSM51FJWBSRJsiUVk8/Gj+rvLTE=";
    };
  }
  {
    name = "N-V-__8AAMQ4CgBbGUjB0KqaRkOJtlQqQfeTuREDWKHGc4Zp";
    path = fetchZigArtifact {
      name = "property_tree";
      url = "git+https://github.com/boostorg/property_tree?ref=boost-1.89.0#2669458cebee100bc1f9f4a9d2f0cd95d07740bc";
      hash = "sha256-1OIOkO9Zild0rOEHN0XR3XuoIB7GiVc9AhMtWPfhMiI=";
    };
  }
  {
    name = "N-V-__8AABj2LAB07zIsWblXUuJFTkspD0QbKKBXpX4zderm";
    path = fetchZigArtifact {
      name = "proto";
      url = "git+https://github.com/boostorg/proto?ref=boost-1.89.0#7f924934689b940f3a72212ab0f714ec6fd6e34b";
      hash = "sha256-RZ3BYAtDIrOpag96S1HeTDfOxAMkba8/KuxswX/mZpI=";
    };
  }
  {
    name = "N-V-__8AAGrKIAB_3_BRvj80Q5dxy6Kicc8DXInk4yjZGBDT";
    path = fetchZigArtifact {
      name = "python";
      url = "git+https://github.com/boostorg/python?ref=boost-1.89.0#3e7be69e1e405e1d5ddd232c69c024ee441592c5";
      hash = "sha256-7N0JhSghU3521kWayPbiFMGYRT1YBH1dms6NzcdHwYo=";
    };
  }
  {
    name = "N-V-__8AAOGGGACoUxgHAU7MfgR-ahJInnG7rh-DSY1QgUvn";
    path = fetchZigArtifact {
      name = "random";
      url = "git+https://github.com/boostorg/random?ref=boost-1.89.0#ce34d1e3685861bca0e5c08f6f0cbe5701aa1266";
      hash = "sha256-pdUF6U8hI1+FTmIev9rsLYkQXfTBMfM3g7oKik9Uxxc=";
    };
  }
  {
    name = "N-V-__8AAMkRGQCRXp9NP8hEMMLkgBB2P43kgCweo_pwE_AP";
    path = fetchZigArtifact {
      name = "range";
      url = "git+https://github.com/boostorg/range?ref=boost-1.89.0#24b7c98ca12708549513adc4770a2cf5586168f9";
      hash = "sha256-iZIY0/29bMuOlXd4YzC0qQ1mnSaPH0Gi24dVo1+i5H0=";
    };
  }
  {
    name = "N-V-__8AACCJCQA-PKyRksmp38bHbdUH9MDctKN5a7BT9uSc";
    path = fetchZigArtifact {
      name = "redis";
      url = "git+https://github.com/boostorg/redis?ref=boost-1.89.0#76129bbcb8373f23d37877fccededb288690eed0";
      hash = "sha256-snh57WH3qK41Z999/E1fR6QD1AJ7r9evssSet9cDdt8=";
    };
  }
  {
    name = "N-V-__8AADAtOgALiWNEOQK6hAmVZigPOHAqILZ7hzNWwGA4";
    path = fetchZigArtifact {
      name = "regex";
      url = "git+https://github.com/boostorg/regex?ref=boost-1.89.0#f439e22ae41fa647bd7de16c2d92deb232593985";
      hash = "sha256-sovIecm5wZw1ZiX2KiBE643MROAHC1f+SbthxpGW09Q=";
    };
  }
  {
    name = "N-V-__8AALNNQQCHJ90BqIiWlYmFjpkaEKejVPYEftqw7gIs";
    path = fetchZigArtifact {
      name = "safe_numerics";
      url = "git+https://github.com/boostorg/safe_numerics?ref=boost-1.89.0#777e0be5ec763d0333a717c5e421a4f7c5e5bdc9";
      hash = "sha256-qrbkdV9BAVlIunMOuRTbLQ4odfYpLWCDNZj23ytcUEs=";
    };
  }
  {
    name = "N-V-__8AADdSBgA8c7rVDjjqRIymq8mGDU15uqYuciLTZyAV";
    path = fetchZigArtifact {
      name = "scope";
      url = "git+https://github.com/boostorg/scope?ref=boost-1.89.0#e286819b43744aa589e6b1937ae0e6f78f038cc7";
      hash = "sha256-5j6Y+7v2scCRXuqWg7bC9unPFEGwQ/F9Dre2y/uNAus=";
    };
  }
  {
    name = "N-V-__8AADOvIQDs5dJOPykAvU8G7JkELrGnc7C0MD4eeFxk";
    path = fetchZigArtifact {
      name = "serialization";
      url = "git+https://github.com/boostorg/serialization?ref=boost-1.89.0#a20c4d97c37e5f437c8ba78f296830edb79cff9e";
      hash = "sha256-JaYkZ4ACmmaiUkNzdPSZWzWRzb9KCZYgZtgLjpiektM=";
    };
  }
  {
    name = "N-V-__8AAKzDCAA4mjzbXNbygO1YuX4mU1AtyOWaAwcoX3rx";
    path = fetchZigArtifact {
      name = "signals2";
      url = "git+https://github.com/boostorg/signals2?ref=boost-1.89.0#898c81affdac7759768f846ea461d2364b028f0e";
      hash = "sha256-chDpBP7qcOZR7c7er5lH9KjjMN94MLAlVO+sI1PjdQs=";
    };
  }
  {
    name = "N-V-__8AAHRTFQAUbTsubOw5Z-ggvK6scbN3NGuA9FUOBcsc";
    path = fetchZigArtifact {
      name = "smart_ptr";
      url = "git+https://github.com/boostorg/smart_ptr?ref=boost-1.89.0#79dac0e691b99e2ba066eba44618ff620a6acfe3";
      hash = "sha256-AdzrB7sIIBJ7VL4MC7b2ks9iihaHwKdEFDYFxutKni4=";
    };
  }
  {
    name = "N-V-__8AAFBjQAB5Dh0pMRlNRizhsX22Y1PHci340kHLL5wn";
    path = fetchZigArtifact {
      name = "sort";
      url = "git+https://github.com/boostorg/sort?ref=boost-1.89.0#1368f28b2f32486c106ff1ec66626938bc5c8e94";
      hash = "sha256-7zIp9pv+gRCFKEEBNUvLzvQ6gadyBARzOvYAHj7tNQY=";
    };
  }
  {
    name = "N-V-__8AAOFKzgCCDxTT2niHOb7wshEyuiLr57U5WKBz3a0R";
    path = fetchZigArtifact {
      name = "spirit";
      url = "git+https://github.com/boostorg/spirit?ref=boost-1.89.0#08b3d033c92238f3c4f8d78e8b4e5b1d90307389";
      hash = "sha256-JQqWG6AEuU5FO3jbdwYtmLYwzPFZzdFz3yBkkc/a628=";
    };
  }
  {
    name = "N-V-__8AAC3_AwAaL1_28mCHHIBafDRXZbptQ9qsZ_W7hqAh";
    path = fetchZigArtifact {
      name = "stacktrace";
      url = "git+https://github.com/boostorg/stacktrace?ref=boost-1.89.0#d6499f26d471158b6e6f65eea7425200f842b547";
      hash = "sha256-7Kqwd7CwhPMXND/EQ+zvjHoDZ51BYXFzhv+kiEYzrUU=";
    };
  }
  {
    name = "N-V-__8AAK7pAACf3O82lupST65fn7dA4KhONnxefg-gqW0z";
    path = fetchZigArtifact {
      name = "static_assert";
      url = "git+https://github.com/boostorg/static_assert?ref=boost-1.89.0#9a6a86efc8dea37083ed1a78fb0998673517cf4e";
      hash = "sha256-J5OUm8Ou74N5cOnaOSinmGk+YPpolWpfWCnaGlvUZUY=";
    };
  }
  {
    name = "N-V-__8AAH6rCgAubWoVbPcLq1Jy3zwrXM8FeP7YED3wJ2pI";
    path = fetchZigArtifact {
      name = "static_string";
      url = "git+https://github.com/boostorg/static_string?ref=boost-1.89.0#bff5cb65a5cb9151aacaf56abe80125e0128f43a";
      hash = "sha256-btJAuuXl2FsWEvG41bSGoH0HIgoGfBhKW3a5eszlJnY=";
    };
  }
  {
    name = "N-V-__8AAG1vCgDmrPdu4aRlIOfLPdLL4ecxxbADvP0oPS4k";
    path = fetchZigArtifact {
      name = "system";
      url = "git+https://github.com/boostorg/system?ref=boost-1.89.0#14c5f52602c172d2ede2dda2c06847f7123b4c77";
      hash = "sha256-XRXaDEbnDSgbaTzlHb4Rf42mU37ODAuBKnpjiwlpP7E=";
    };
  }
  {
    name = "N-V-__8AAHDbAQBbTOh_gXYOheNgjIYnjBag1HqSfLJNb546";
    path = fetchZigArtifact {
      name = "throw_exception";
      url = "git+https://github.com/boostorg/throw_exception?ref=boost-1.89.0#f3d4d55f52894fda75ef2915dc122e3133b97b45";
      hash = "sha256-kX0kizEaDbcmpGmm/DWN6kZieyWe0HtnXHdmN+mKYjE=";
    };
  }
  {
    name = "N-V-__8AAGBTAgBqTK9eFPUQtClpOyyCk9T8Uj_i8NuaU6Lw";
    path = fetchZigArtifact {
      name = "timer";
      url = "git+https://github.com/boostorg/timer?ref=boost-1.89.0#b7f65f09a0975f26cb294eebd8b17e91a5beff3f";
      hash = "sha256-2i79rJBIkOhZuzM+pivcmyM6XdwBuaiQ0G80iNbKVVI=";
    };
  }
  {
    name = "N-V-__8AAMjfAQCFd7AbC0oR2nywxgUAoeLd1PnpMKIv7gtL";
    path = fetchZigArtifact {
      name = "tokenizer";
      url = "git+https://github.com/boostorg/tokenizer?ref=boost-1.89.0#a1207c1a424ee565344fe5ef00605cb93f5210c2";
      hash = "sha256-xjnAXQ+c7G6CMB1RggAERkCdh0+2rKMAIv28dDScEfk=";
    };
  }
  {
    name = "N-V-__8AAOZmCADODeMFdbLe1jAS_JVYPMQ3d3Jc3JyfDul9";
    path = fetchZigArtifact {
      name = "tti";
      url = "git+https://github.com/boostorg/tti?ref=boost-1.89.0#03734c54a51b6372ac3296d2fe5103b7360bcd3f";
      hash = "sha256-o2kdpe1nEs6/GZhL8eRN+/Ec74fu6/MkH6I3Cy+Mpck=";
    };
  }
  {
    name = "N-V-__8AAEorAgCGS_LIouQeOsTxNG0EcEwJ7-qYne288zDW";
    path = fetchZigArtifact {
      name = "tuple";
      url = "git+https://github.com/boostorg/tuple?ref=boost-1.89.0#d04e4a692fda32f939edede89d67e4b2234f0da9";
      hash = "sha256-2PTGblaitDEhy/XvThETYyeAz2A2lDFvWfQ/atT8mn0=";
    };
  }
  {
    name = "N-V-__8AAP5SDQBITJgI5Jcyk3yGlFe0b_TqZIsjDZUydiC6";
    path = fetchZigArtifact {
      name = "type_erasure";
      url = "git+https://github.com/boostorg/type_erasure?ref=boost-1.89.0#5281f14d3cb59f978c8cb6cbb90ce92dde4e3e13";
      hash = "sha256-XDj8X0A92d3Fy+zCfJl71T2/GNGn4OVDybwx30RJVns=";
    };
  }
  {
    name = "N-V-__8AAE0aAwB7fVrtwJcuKTVOzHjERHeBMxAOk78MnT92";
    path = fetchZigArtifact {
      name = "type_index";
      url = "git+https://github.com/boostorg/type_index?ref=boost-1.89.0#32dcf01725eb07d17e0bc2d55248b9609280896c";
      hash = "sha256-3njyTPlLV79AAeFoHXSBVFy98k3DFTZpfnIfnWOI4to=";
    };
  }
  {
    name = "N-V-__8AAHxrWADA1j6sqfZ-J9z9gXyL82-Nsp0zA8uASHtS";
    path = fetchZigArtifact {
      name = "type_traits";
      url = "git+https://github.com/boostorg/type_traits?ref=boost-1.89.0#67a6c32499866ea4485e249e8e406fb1348eb5d2";
      hash = "sha256-OH9x0V8WzASXYFwIPs3RAA4O1JD4dEm5wEjndpAM0T4=";
    };
  }
  {
    name = "N-V-__8AAC6jAQDBN1fyK8R1P3xdDSLDLnF_hu7wROXZvAtC";
    path = fetchZigArtifact {
      name = "typeof";
      url = "git+https://github.com/boostorg/typeof?ref=boost-1.89.0#26e22b8b370617a6181f3ae4bd1f584b3b4767e1";
      hash = "sha256-4dxXZiFD8EYspB6Cdm+qEAhnenhgx9Hs0cC/Rwy+DQc=";
    };
  }
  {
    name = "N-V-__8AAK5-OwAjoTGZtX_qcfh6hQDM2cbkRbPXD7fxu8hY";
    path = fetchZigArtifact {
      name = "ublas";
      url = "git+https://github.com/boostorg/ublas?ref=boost-1.89.0#15d871b410ff92592c6f3e0a53550035e7817046";
      hash = "sha256-6klr9JqynTk/OMoVWZQM0x2EAgXh3+55VjE1Gl1MYI4=";
    };
  }
  {
    name = "N-V-__8AABVFEQDkg4mMFIiUaipuch30aW7TQdxy4hCE2X7e";
    path = fetchZigArtifact {
      name = "units";
      url = "git+https://github.com/boostorg/units?ref=boost-1.89.0#45787015dd8c11653eb988260acf05c4af9d42e5";
      hash = "sha256-fjiO9rnljUqM0LZtKbILxvj+UHL0eNGmLQeCn6yk/bo=";
    };
  }
  {
    name = "N-V-__8AAOM4fACNeZypFqiZCciOJhBPWiRT4ffcpQniLMox";
    path = fetchZigArtifact {
      name = "unordered";
      url = "git+https://github.com/boostorg/unordered?ref=boost-1.89.0#59e2a562edf0759e0ac52f659d25e0907ed7bec6";
      hash = "sha256-SwbBN3WojEitxGfXVkHFAFVEFmmeFm8abnJw5hsPqd4=";
    };
  }
  {
    name = "N-V-__8AAJdoWwC2cyp_jJ2plRE9KnBTkdESqTkr4Stcx8gf";
    path = fetchZigArtifact {
      name = "url";
      url = "git+https://github.com/boostorg/url?ref=boost-1.89.0#8d5cc6e34884b4f3a8a43c8f9706c0f5800238a0";
      hash = "sha256-lTxGqPwaVP4G+d2lEoolzbVYZI9Ahfy/zb6EGNd6Atw=";
    };
  }
  {
    name = "N-V-__8AAM7xDAAh6UgGfBTGzSd5M2Y3EAYXVo_lz03cb4H-";
    path = fetchZigArtifact {
      name = "utility";
      url = "git+https://github.com/boostorg/utility?ref=boost-1.89.0#211570f2b972f66e368e4fe32b00fee31e597d25";
      hash = "sha256-jCO+VDInIIV0gPePl6zambgmjflD/uuJvdetqSVGTE4=";
    };
  }
  {
    name = "N-V-__8AACuDBQBtvGvutYvKEqSBoYBcsvXoKIT9HWc45ajd";
    path = fetchZigArtifact {
      name = "uuid";
      url = "git+https://github.com/boostorg/uuid?ref=boost-1.89.0#434329f8dc7fcfb69cd7565ab0318d86772cea39";
      hash = "sha256-50AGx3jqGodZcVyAcpMWSmXjwFoUEE9b5DYZEWNZgJc=";
    };
  }
  {
    name = "N-V-__8AAI4vCADtGWf9KnoRUc6iyfyJTzCDTSoRISmzg6nO";
    path = fetchZigArtifact {
      name = "variant";
      url = "git+https://github.com/boostorg/variant?ref=boost-1.89.0#1fd7271d2e34a36f010f8882fdde703ad9a4ffeb";
      hash = "sha256-ttj+UUHWtRaDucaR7XxBbelg4fLzOUpL5qyQdIPBH7E=";
    };
  }
  {
    name = "N-V-__8AAEhxBgALKUq3Mxdhm8dJwedU_g0x2adiWEotdsDv";
    path = fetchZigArtifact {
      name = "variant2";
      url = "git+https://github.com/boostorg/variant2?ref=boost-1.89.0#8caa1a34843951b9e4e302dc85e90bc19ca4f3dd";
      hash = "sha256-CdsNTYYqhZEEoZ/LAPlOxDr9YPG3VQy9Iz4VJ71STl4=";
    };
  }
  {
    name = "N-V-__8AALO0MwBElcnzmpmvZb57SyPoGw_68--ZJx11tj7o";
    path = fetchZigArtifact {
      name = "wave";
      url = "git+https://github.com/boostorg/wave?ref=boost-1.89.0#d7aa5a369d8f2faf48c8ea16ba041dfabbf91363";
      hash = "sha256-ZzFZ0NApJk/cXie9pSJTU5iea8pnkYp3zos6KueceUo=";
    };
  }
  {
    name = "N-V-__8AABa1DgAIZmdXipk8huTt1Vn8HdO7kd5MwALLNknl";
    path = fetchZigArtifact {
      name = "winapi";
      url = "git+https://github.com/boostorg/winapi?ref=boost-1.89.0#bbd9bf65857bcf48fd2f90fecf077a192ee29be8";
      hash = "sha256-bqgQoKsXrXj3GeHdE0TM34VCXPkydLrUlXEhWb1lwiw=";
    };
  }
]
