# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAA446gD7kQ4vIk7qwv3fmTLLki4Og8IY9XPQ2Iit";
    path = fetchgit {
      url = "https://github.com/boostorg/asio?ref=boost-1.89.0";
      rev = "f529dbbd6156b57f079f1387768b585a37d0f621";
      hash = "sha256-YGMCR5he/HlFsVDuIo9Q3KwFaEHnSfJAKtCyRaQzNuE=";
    };
  }
  {
    name = "N-V-__8AAA72FQD6Y5k_wYXL6pRzLLVEF8mk_gxK99GmDtDK";
    path = fetchgit {
      url = "https://github.com/boostorg/pfr?ref=boost-1.89.0";
      rev = "5034bf55fb6bd1efa7a14955bbb7171c2b3491fc";
      hash = "sha256-0K19WybKaitw+TX5BQhCcmhfWkwmU/uEirdkrWQt55Q=";
    };
  }
  {
    name = "N-V-__8AAAYbSABEngHJeWbJCaDFDOxpNEIStZP1Bm5i6LR5";
    path = fetchgit {
      url = "https://github.com/boostorg/fiber?ref=boost-1.89.0";
      rev = "238487b543e8863c647d31a82ccfc3fa11a960d9";
      hash = "sha256-JpyVVA2528nfCsYSl0r58E6uw+V7OrXSHb3UBwLRoE8=";
    };
  }
  {
    name = "N-V-__8AAAbXBgD7zMewPCjTL30k9q0XSXKrn4v2UoiKLByB";
    path = fetchgit {
      url = "https://github.com/boostorg/optional?ref=boost-1.89.0";
      rev = "121f3efde91de78ca018019904732f55d33b5788";
      hash = "sha256-lzxlgrZ6FcFZ3Ix4EZio2VYAHYEkhcqHKp5H+Pk7j6s=";
    };
  }
  {
    name = "N-V-__8AAAieLgDl61ANGt1eaCLj0oYtzF3PZ5Wzzr-1bD3s";
    path = fetchgit {
      url = "https://github.com/boostorg/pool?ref=boost-1.89.0";
      rev = "740c8076f9d02f0216e8f3dbb15d2fd80f67d7f4";
      hash = "sha256-z6s20Gm8Kq7/26G8I53Z92kHvwoHRUO6I9PQ/DgrGGY=";
    };
  }
  {
    name = "N-V-__8AABVFEQDkg4mMFIiUaipuch30aW7TQdxy4hCE2X7e";
    path = fetchgit {
      url = "https://github.com/boostorg/units?ref=boost-1.89.0";
      rev = "45787015dd8c11653eb988260acf05c4af9d42e5";
      hash = "sha256-I3Mb3pdhSM2NbMrxm89gF0jxIgP9WHCtWazQP/u7XF0=";
    };
  }
  {
    name = "N-V-__8AABa1DgAIZmdXipk8huTt1Vn8HdO7kd5MwALLNknl";
    path = fetchgit {
      url = "https://github.com/boostorg/winapi?ref=boost-1.89.0";
      rev = "bbd9bf65857bcf48fd2f90fecf077a192ee29be8";
      hash = "sha256-p1s5xMfZ075K1KJreHky6zrpZ+PbcP/1mZrHLvPmMrI=";
    };
  }
  {
    name = "N-V-__8AABj2LAB07zIsWblXUuJFTkspD0QbKKBXpX4zderm";
    path = fetchgit {
      url = "https://github.com/boostorg/proto?ref=boost-1.89.0";
      rev = "7f924934689b940f3a72212ab0f714ec6fd6e34b";
      hash = "sha256-+YCWlvHxfJ4fJ7IfcMpIVPBTsL6462QrI+2Ne6voSHQ=";
    };
  }
  {
    name = "N-V-__8AABpViQDRvjP80WTO508uOFMp2xkI5xzYFM2lK-I4";
    path = fetchgit {
      url = "https://github.com/boostorg/mpl?ref=boost-1.89.0";
      rev = "74d927f9847c60b908beac94e1198d1985380abf";
      hash = "sha256-XzPGr2dRyhcqDaz4mDQ85kqC8BZ69XmYhIJ/8nv1Nq8=";
    };
  }
  {
    name = "N-V-__8AABqQAwBjPZPQUVcSVlq2U4qbpVlTcMmpHvPCzzdu";
    path = fetchgit {
      url = "https://github.com/boostorg/detail?ref=boost-1.89.0";
      rev = "43238b75cee1a010d6ef6dc48dfc21c365d3796f";
      hash = "sha256-fIzpgxLVaB0EPknG5X6pH9qf+XysKDeWOlzBJKBDiDE=";
    };
  }
  {
    name = "N-V-__8AABq_DgC0lnu8by8GZoGFe0a6uusmJuZ8U3WU_g0r";
    path = fetchgit {
      url = "https://github.com/boostorg/cobalt?ref=boost-1.89.0";
      rev = "57181cacc5b8d5079d95a33b7aa078d0f5f16147";
      hash = "sha256-rMx17QQhPaSimLSHRQfez7dorCdLkfJbmbKZO6XioEc=";
    };
  }
  {
    name = "N-V-__8AAC1wSgBqFydUHgmzFQVVdXrHxrJoLKCBMqkxZ9L9";
    path = fetchgit {
      url = "https://github.com/boostorg/container?ref=boost-1.89.0";
      rev = "e8baf848bc426022dffbc814db8e1261d6033d4b";
      hash = "sha256-XLYQ2+y49IX8/EIDpjGfT0gXwf6v0XJdTVIXahv8M/k=";
    };
  }
  {
    name = "N-V-__8AAC21DwAnTqvk8h56Tf6exNRnueYJ3qdnHCAGu8PJ";
    path = fetchgit {
      url = "https://github.com/boostorg/leaf?ref=boost-1.89.0";
      rev = "aff38b5be343ac6f1588e3258d126224e5347934";
      hash = "sha256-hzgPYJKm0a+dyQsEFr6giBc9ptVR5GUxFOMlxgTi2Ak=";
    };
  }
  {
    name = "N-V-__8AAC3_AwAaL1_28mCHHIBafDRXZbptQ9qsZ_W7hqAh";
    path = fetchgit {
      url = "https://github.com/boostorg/stacktrace?ref=boost-1.89.0";
      rev = "d6499f26d471158b6e6f65eea7425200f842b547";
      hash = "sha256-nW0PRqcXl6/mx765ETae81/LKaVBrH6rKkBFH6no2xA=";
    };
  }
  {
    name = "N-V-__8AAC6jAQDBN1fyK8R1P3xdDSLDLnF_hu7wROXZvAtC";
    path = fetchgit {
      url = "https://github.com/boostorg/typeof?ref=boost-1.89.0";
      rev = "26e22b8b370617a6181f3ae4bd1f584b3b4767e1";
      hash = "sha256-4dxXZiFD8EYspB6Cdm+qEAhnenhgx9Hs0cC/Rwy+DQc=";
    };
  }
  {
    name = "N-V-__8AACBiRQA64_Vr35VyzPDnQ7Dr1W7A1ANPoHYMRe1W";
    path = fetchgit {
      url = "https://github.com/boostorg/outcome?ref=boost-1.89.0";
      rev = "9fab401aa0ee4e578ec6757c082b6f66c67a55c7";
      hash = "sha256-L4HFHabpgbsACxRVqCiXRxE6QYdgAWdNPypKElxVA6I=";
    };
  }
  {
    name = "N-V-__8AACCJCQA-PKyRksmp38bHbdUH9MDctKN5a7BT9uSc";
    path = fetchgit {
      url = "https://github.com/boostorg/redis?ref=boost-1.89.0";
      rev = "76129bbcb8373f23d37877fccededb288690eed0";
      hash = "sha256-t6xJ7Cy2TRm02vAD7o9tuDrY1+/4p8vmvAcq2PZVCVg=";
    };
  }
  {
    name = "N-V-__8AACHiCQC1YZI5LZX4OT7n2FGUQSB9SSMSOUX1LMIn";
    path = fetchgit {
      url = "https://github.com/boostorg/numeric_conversion?ref=boost-1.89.0";
      rev = "d1b479f7a4aa54d8ffb93d8dc4ee0c24670210d8";
      hash = "sha256-u9v7e7yLKsfiV8Btz4+hKNR9eI7BTFK7AWte8oGvreg=";
    };
  }
  {
    name = "N-V-__8AACUhPQDA5Mvi9LLrRdKvMv8hAerVBZWKQkfHSqn1";
    path = fetchgit {
      url = "https://github.com/boostorg/algorithm?ref=boost-1.89.0";
      rev = "32c5a6327cfdca5d41ce0f1d8849b811886daa2f";
      hash = "sha256-KvH+DEMqpAQcs9p0EkmwdCEKgxgs2UA0eVM7ryjiC3M=";
    };
  }
  {
    name = "N-V-__8AACbVJAB945DbAOb-qVUoGDlIZDUl75YagkF5R5jA";
    path = fetchgit {
      url = "https://github.com/boostorg/odeint?ref=boost-1.89.0";
      rev = "9e75be5d9e435739b086aee928736fc241e77a4a";
      hash = "sha256-N0gzvfWscMW0L5fomJCR12HwlyR0RA3E/iueqgDLAnU=";
    };
  }
  {
    name = "N-V-__8AACeoAwDBhzf1Wp8HsLSDiKoijtb2R2i0X_0mVcCh";
    path = fetchgit {
      url = "https://github.com/boostorg/integer?ref=boost-1.89.0";
      rev = "0fefe9831abf014d3a7da7172755aae0f54e85f0";
      hash = "sha256-0DmBC12XtGkkWPuPMRQXDjhsC2OFPel8KzBVnAu95to=";
    };
  }
  {
    name = "N-V-__8AACuDBQBtvGvutYvKEqSBoYBcsvXoKIT9HWc45ajd";
    path = fetchgit {
      url = "https://github.com/boostorg/uuid?ref=boost-1.89.0";
      rev = "434329f8dc7fcfb69cd7565ab0318d86772cea39";
      hash = "sha256-kgPobjiU6Bc+eY5T/8DT1tK0IoDLF8EWfRrddNAeLyo=";
    };
  }
  {
    name = "N-V-__8AAD5JAwBeVXAdgiQK80Ee_0gbp4P0gCNJ3s9rpU1a";
    path = fetchgit {
      url = "https://github.com/boostorg/property_map?ref=boost-1.89.0";
      rev = "830cb6bce0b54fc1b2d7806901c1b8c8716964b7";
      hash = "sha256-sKBT5SZBM2zeGQf8L/WGyJDrDeKWMcXkxdMFCCY582c=";
    };
  }
  {
    name = "N-V-__8AADAtOgALiWNEOQK6hAmVZigPOHAqILZ7hzNWwGA4";
    path = fetchgit {
      url = "https://github.com/boostorg/regex?ref=boost-1.89.0";
      rev = "f439e22ae41fa647bd7de16c2d92deb232593985";
      hash = "sha256-MmVM1aJdVIXujRtC6BI9N53LzDZ4uUqCFLiLVxCcsME=";
    };
  }
  {
    name = "N-V-__8AADN2FwCbU_54Zgoc765ecy_CfPCwIlBhh628Dg0A";
    path = fetchgit {
      url = "https://github.com/boostorg/filesystem?ref=boost-1.89.0";
      rev = "d316a9d3aa09bb3d200646cc587a16e3b9be5f39";
      hash = "sha256-IfQZfUioqYgAoX2g+hitCM7hNCspClRsemPZcO6jvOM=";
    };
  }
  {
    name = "N-V-__8AADOWEAAMuUSjDb6dpGa4US3dPfF2z4QecdQrOusY";
    path = fetchgit {
      url = "https://github.com/boostorg/core?ref=boost-1.89.0";
      rev = "a128501403c08d70475cc87c4e511b59744b1aa1";
      hash = "sha256-HDhZQPygS3hhNE1LVBpUXIJTZoLk9bqS0mOlhkgUZpQ=";
    };
  }
  {
    name = "N-V-__8AADOvIQDs5dJOPykAvU8G7JkELrGnc7C0MD4eeFxk";
    path = fetchgit {
      url = "https://github.com/boostorg/serialization?ref=boost-1.89.0";
      rev = "a20c4d97c37e5f437c8ba78f296830edb79cff9e";
      hash = "sha256-oMDsPfGJK84B8XtUBZML+Ujp0Yb5OnebevWncuV7adA=";
    };
  }
  {
    name = "N-V-__8AADTThQCR3QabRhSONgDag-0YZ2ZhtCvqZnTdmael";
    path = fetchgit {
      url = "https://github.com/boostorg/iostreams?ref=boost-1.89.0";
      rev = "8561bdb8bcd0a1b528d60c090407233b0c1d9148";
      hash = "sha256-06nyC2gTshoIj4DFy0SPdND0FyKmhdYxjlRAdFJ15Ug=";
    };
  }
  {
    name = "N-V-__8AADVmDABcDKw_D3-FlptU7zo0958BFPZBvuRT0d9E";
    path = fetchgit {
      url = "https://github.com/boostorg/move?ref=boost-1.89.0";
      rev = "40d2be68bae9acfb4f165cdaab0a4246c5af5485";
      hash = "sha256-b4wt0CPixK2FygAREnMhLxasGiSwASrexUB5qpRqVeU=";
    };
  }
  {
    name = "N-V-__8AADdSBgA8c7rVDjjqRIymq8mGDU15uqYuciLTZyAV";
    path = fetchgit {
      url = "https://github.com/boostorg/scope?ref=boost-1.89.0";
      rev = "e286819b43744aa589e6b1937ae0e6f78f038cc7";
      hash = "sha256-874Rsb4NdXeS6xe8koz00ZVNmDlsApO7RtI0h871nVU=";
    };
  }
  {
    name = "N-V-__8AADeWBACdc4-qLylEme_d0C7JkljJh5TukDftAjNI";
    path = fetchgit {
      url = "https://github.com/boostorg/coroutine2?ref=boost-1.89.0";
      rev = "dbbf042e0a9081b4119d491b788ae0fe7c03192a";
      hash = "sha256-gaHzhfWggNqAHW2fRefivycTPc71f4glaS7gvJeJRjY=";
    };
  }
  {
    name = "N-V-__8AADlcNQDhH366SuEkCxtTVAsvndumYUvXxtSEcoKu";
    path = fetchgit {
      url = "https://github.com/boostorg/log?ref=boost-1.89.0";
      rev = "ad2eb6c4e54ebefb667fac25672bdd723fe55f37";
      hash = "sha256-hkVIvyOZ02upXRPfr5nL0JWrF2rKOnPM7AtEr7PMrEM=";
    };
  }
  {
    name = "N-V-__8AADr6AwBPtdKdJXDzLN24sfh_A-Ln0CEymC5BGrfo";
    path = fetchgit {
      url = "https://github.com/boostorg/describe?ref=boost-1.89.0";
      rev = "b64177c39f929998e3a145992d0328712e095c29";
      hash = "sha256-6DQOpYH2FvA2ui7wIFIm4DUPL0fikIQc0c9b+26efzI=";
    };
  }
  {
    name = "N-V-__8AADyLAQB5o2e2wLaIFkmW8NQ9NAo0Se1kEokyRggG";
    path = fetchgit {
      url = "https://github.com/boostorg/logic?ref=boost-1.89.0";
      rev = "9b8703a2d6623405323b892f1d126a6b17ca1651";
      hash = "sha256-UFOLBkSDJ/+o3rn1Af4tSsWaaV+bvnMIj6sUDL51j/s=";
    };
  }
  {
    name = "N-V-__8AADz7RAYjVkkNadLVj35VD5OjXs7r2N1RR6Cdjxab";
    path = fetchgit {
      url = "https://github.com/boostorg/math?ref=boost-1.89.0";
      rev = "5e088ffe2ed0e237b9069e3a7352865283d8f196";
      hash = "sha256-DHyn3iSxBPtzWx22Pl5coBicAIx4tzm6O1IAgmEGhPA=";
    };
  }
  {
    name = "N-V-__8AAE0aAwB7fVrtwJcuKTVOzHjERHeBMxAOk78MnT92";
    path = fetchgit {
      url = "https://github.com/boostorg/type_index?ref=boost-1.89.0";
      rev = "32dcf01725eb07d17e0bc2d55248b9609280896c";
      hash = "sha256-4EJhzd6aTLhk1TzwG6TgBYNF/eFvvOO//eWh2+kgZnk=";
    };
  }
  {
    name = "N-V-__8AAE3GCACIRxAD3oWteML3w5sBwmm_njj5DG6cwX-Z";
    path = fetchgit {
      url = "https://github.com/boostorg/endian?ref=boost-1.89.0";
      rev = "c0b5c80603b8de7eeea8724c9a4f2761c3df06f2";
      hash = "sha256-fpG5BghLPZAKJuDqFHHaYjWrQ5bXveQMMQv/oFlhjbA=";
    };
  }
  {
    name = "N-V-__8AAE6TewG5DeroUp9WPc2kWZPN9Nlb1CcbAhUYNtrp";
    path = fetchgit {
      url = "https://github.com/boostorg/geometry?ref=boost-1.89.0";
      rev = "617d75e0cda78b1f05590319200973514b609097";
      hash = "sha256-VLt2uqWZ4u/GsEhXtnIKrTmKgJQdSpxgXOfy2x9v2Bw=";
    };
  }
  {
    name = "N-V-__8AAEhxBgALKUq3Mxdhm8dJwedU_g0x2adiWEotdsDv";
    path = fetchgit {
      url = "https://github.com/boostorg/variant2?ref=boost-1.89.0";
      rev = "8caa1a34843951b9e4e302dc85e90bc19ca4f3dd";
      hash = "sha256-UVk2sc5J4dWI6OBfXXRMrsYg/ySbYgRq0FZZlrStc3s=";
    };
  }
  {
    name = "N-V-__8AAEjTAwB6uQ-nvXSJyu_Gzsk-5lgG4fcJ_-4mfaZV";
    path = fetchgit {
      url = "https://github.com/boostorg/crc?ref=boost-1.89.0";
      rev = "75146a958410c789381a4609166c754d35548e2d";
      hash = "sha256-PeCMDZX9Iwoi/R8HFYMgOL4EOiyjDnaUma4SnRc5xIk=";
    };
  }
  {
    name = "N-V-__8AAEorAgCGS_LIouQeOsTxNG0EcEwJ7-qYne288zDW";
    path = fetchgit {
      url = "https://github.com/boostorg/tuple?ref=boost-1.89.0";
      rev = "d04e4a692fda32f939edede89d67e4b2234f0da9";
      hash = "sha256-2PTGblaitDEhy/XvThETYyeAz2A2lDFvWfQ/atT8mn0=";
    };
  }
  {
    name = "N-V-__8AAEqrCgDamRDkhpeo431rBpKsRdNmJVEJ4L3xaF1x";
    path = fetchgit {
      url = "https://github.com/boostorg/bind?ref=boost-1.89.0";
      rev = "a541a8d5c16920e1836d09299915890d687efe36";
      hash = "sha256-tAJNR99ZRouSwZZSupwvi/iDAv4Ax/h8p7trLtriIHU=";
    };
  }
  {
    name = "N-V-__8AAFBjQAB5Dh0pMRlNRizhsX22Y1PHci340kHLL5wn";
    path = fetchgit {
      url = "https://github.com/boostorg/sort?ref=boost-1.89.0";
      rev = "1368f28b2f32486c106ff1ec66626938bc5c8e94";
      hash = "sha256-f3O/vuH8hYeoWDYtZ6N/lfD7Os9Wyr3TnpnfntfnURE=";
    };
  }
  {
    name = "N-V-__8AAF_HAAAa2M3jMn8cCdW6jOG3mNdWlDp6AFotkaIL";
    path = fetchgit {
      url = "https://github.com/boostorg/conversion?ref=boost-1.89.0";
      rev = "b74a4c34cb181a8a26d35d05fab608426449626a";
      hash = "sha256-AvgvLhQBWNmxzJswYHHnaksNLLiS0DjvEJH3nFPHfhA=";
    };
  }
  {
    name = "N-V-__8AAFlMAgBlNIseNerkSVmUC9TxOlWrCI7SA6j_v4uz";
    path = fetchgit {
      url = "https://github.com/boostorg/array?ref=boost-1.89.0";
      rev = "e988ef9c4a7d64be2850dc8de18b6461e094d4ae";
      hash = "sha256-P7pFHRtIkmDxWv3Oq5xul5l2eh2zX6rAr6/24pk/daY=";
    };
  }
  {
    name = "N-V-__8AAFsNGgB3V1msMNp3dMgDlxSplQS2LANIzqhi3OvZ";
    path = fetchgit {
      url = "https://github.com/boostorg/context?ref=boost-1.89.0";
      rev = "3af0091efa65892e030add013417840f80b13e08";
      hash = "sha256-7tNOHtu7dvnUGUhWCIHTCJERIdk1AGhNJyqfLJDlVKU=";
    };
  }
  {
    name = "N-V-__8AAFuJAQDT6Xjpc49iuweYnJ4j4UM3h134E7SjgK2W";
    path = fetchgit {
      url = "https://github.com/boostorg/io?ref=boost-1.89.0";
      rev = "342e4c6d10d586058818daa84201a2d301357a53";
      hash = "sha256-qlH5wwYcmNQ090ydzONtWhDCGG21VkUFjAl8y4hGgos=";
    };
  }
  {
    name = "N-V-__8AAFycUwBUUnF2yUTADUwmx3-NW3GtNEQFb7wBzgIv";
    path = fetchgit {
      url = "https://github.com/boostorg/msm?ref=boost-1.89.0";
      rev = "33e77cbfc70956d4b99f3dfc9c1e83848fe2550b";
      hash = "sha256-ZfYCDi/sclw7a/OHa0KqLT/w4e0UFsRD8UFKCpqhUnA=";
    };
  }
  {
    name = "N-V-__8AAG1vCgDmrPdu4aRlIOfLPdLL4ecxxbADvP0oPS4k";
    path = fetchgit {
      url = "https://github.com/boostorg/system?ref=boost-1.89.0";
      rev = "14c5f52602c172d2ede2dda2c06847f7123b4c77";
      hash = "sha256-gYuZjmgQoaMBQhJ50YaqqeXmwrIWD9KH0gVPbkIf8oU=";
    };
  }
  {
    name = "N-V-__8AAGBTAgBqTK9eFPUQtClpOyyCk9T8Uj_i8NuaU6Lw";
    path = fetchgit {
      url = "https://github.com/boostorg/timer?ref=boost-1.89.0";
      rev = "b7f65f09a0975f26cb294eebd8b17e91a5beff3f";
      hash = "sha256-2i79rJBIkOhZuzM+pivcmyM6XdwBuaiQ0G80iNbKVVI=";
    };
  }
  {
    name = "N-V-__8AAGCELwBEBL5NQiILNJoVf81b7n1hP0XgDA0wezX2";
    path = fetchgit {
      url = "https://github.com/boostorg/parser?ref=boost-1.89.0";
      rev = "c674e94c3d409b6ab0ee05429361e8b50fe30320";
      hash = "sha256-i8ZCBowNgj6sw9dSL1m+v5aPpYy1fTUfMNudMonS4DA=";
    };
  }
  {
    name = "N-V-__8AAGThJwBWc_L1fi6RFm_jHgif_MY2haphDzC03gJK";
    path = fetchgit {
      url = "https://github.com/boostorg/config?ref=boost-1.89.0";
      rev = "bf8c8bd7960cd8505210838f86bd28fb4fb71071";
      hash = "sha256-sRP0yDTVnu5jX5Pjp+Lwcgm2TXYvpK+u5gByG309vE4=";
    };
  }
  {
    name = "N-V-__8AAGkzAQAB_B7Hu8v4b6LLy_b17j8t4kcFfZznwv51";
    path = fetchgit {
      url = "https://github.com/boostorg/property_map_parallel?ref=boost-1.89.0";
      rev = "a2f90e9660e4e7e012c0b54a1338d8e69fb71906";
      hash = "sha256-3mjL8/R5hfQQTXQ0ejghMB3nc/frnJplhRHeGbjAEFE=";
    };
  }
  {
    name = "N-V-__8AAGrKIAB_3_BRvj80Q5dxy6Kicc8DXInk4yjZGBDT";
    path = fetchgit {
      url = "https://github.com/boostorg/python?ref=boost-1.89.0";
      rev = "3e7be69e1e405e1d5ddd232c69c024ee441592c5";
      hash = "sha256-D/6s9Bo4glfkIFlh3Hid7OxQIdW4J9pZIg2zBZ2lNHU=";
    };
  }
  {
    name = "N-V-__8AAGu-BABbjN6CgUc_0vHRqCMd3v7bNbI_zPUWZimO";
    path = fetchgit {
      url = "https://github.com/boostorg/format?ref=boost-1.89.0";
      rev = "66075102416bc5d0f8e0bd151a19013dadbf94ce";
      hash = "sha256-S8pDsx4OAdV2YmoplrRKDGZmdsd8wVx2sj/B8jgDqbo=";
    };
  }
  {
    name = "N-V-__8AAH6rCgAubWoVbPcLq1Jy3zwrXM8FeP7YED3wJ2pI";
    path = fetchgit {
      url = "https://github.com/boostorg/static_string?ref=boost-1.89.0";
      rev = "bff5cb65a5cb9151aacaf56abe80125e0128f43a";
      hash = "sha256-Ry2sabI80Zc8YE+9O3poirqSngJsweJjyKhiqSAEOHg=";
    };
  }
  {
    name = "N-V-__8AAHDbAQBbTOh_gXYOheNgjIYnjBag1HqSfLJNb546";
    path = fetchgit {
      url = "https://github.com/boostorg/throw_exception?ref=boost-1.89.0";
      rev = "f3d4d55f52894fda75ef2915dc122e3133b97b45";
      hash = "sha256-kqpcApJQv9vbhRF0YyVuHJtv6J+hvlve9KuzWHyxLT8=";
    };
  }
  {
    name = "N-V-__8AAHGaFQDt5k8TphnVwa6vACn9SjMFY-sjx1bHeyhn";
    path = fetchgit {
      url = "https://github.com/boostorg/local_function?ref=boost-1.89.0";
      rev = "258aeaa6c1a9618c02ca4e4af2890e70833035f0";
      hash = "sha256-id8sr+ufESd4Y7kgw/GdU1mU+HScQBnozV48G5Mp4VE=";
    };
  }
  {
    name = "N-V-__8AAHKoEgC2FVY0dM8korgUTF2zl2VwWnrFCaE5RHS8";
    path = fetchgit {
      url = "https://github.com/boostorg/chrono?ref=boost-1.89.0";
      rev = "ef510872039483dc66b7b2263c43c273a9aaecd6";
      hash = "sha256-AK5kbnidHvzGpUd/VU4RPrsJsbQ2rB8obyJOa4ZrWMc=";
    };
  }
  {
    name = "N-V-__8AAHRTFQAUbTsubOw5Z-ggvK6scbN3NGuA9FUOBcsc";
    path = fetchgit {
      url = "https://github.com/boostorg/smart_ptr?ref=boost-1.89.0";
      rev = "79dac0e691b99e2ba066eba44618ff620a6acfe3";
      hash = "sha256-JbqPxNwjwS1edYyCGhmgsM8miTQzPcF59P+ib6k3zIg=";
    };
  }
  {
    name = "N-V-__8AAHUVBwBno0N-AuY5GL3NvDJCBDlWTIVae25QBzSE";
    path = fetchgit {
      url = "https://github.com/boostorg/dll?ref=boost-1.89.0";
      rev = "4105c3a8f8d5287b59b0185c45d4c9a768d92a55";
      hash = "sha256-8tVHnmztHFGeVkjqqAl+QxmJnZ+Caa4w9hFHqAARkv0=";
    };
  }
  {
    name = "N-V-__8AAHx_BwCNYH9hpUM0OlDZWkGXywYtZ0of3GeRYvci";
    path = fetchgit {
      url = "https://github.com/boostorg/nowide?ref=boost-1.89.0";
      rev = "b2f5f57fdb38ca42bc33b55d5e9cd7024e355399";
      hash = "sha256-H/IClyzuu1yGBYwmu7LMY73oY2DiA0TX7RGWV6TBOyc=";
    };
  }
  {
    name = "N-V-__8AAHxrWADA1j6sqfZ-J9z9gXyL82-Nsp0zA8uASHtS";
    path = fetchgit {
      url = "https://github.com/boostorg/type_traits?ref=boost-1.89.0";
      rev = "67a6c32499866ea4485e249e8e406fb1348eb5d2";
      hash = "sha256-OH9x0V8WzASXYFwIPs3RAA4O1JD4dEm5wEjndpAM0T4=";
    };
  }
  {
    name = "N-V-__8AAHz5BAAHbQ1m2VR4nU0pzxbDjelQBNnSmWDxZvAp";
    path = fetchgit {
      url = "https://github.com/boostorg/functional?ref=boost-1.89.0";
      rev = "6a573e4b8333ee63ee62ce95558c3667348db233";
      hash = "sha256-KXC7bNXw6/8YFA5SqTHIvnnxS3g0Ne3tXIRwEU27c08=";
    };
  }
  {
    name = "N-V-__8AAI4vCADtGWf9KnoRUc6iyfyJTzCDTSoRISmzg6nO";
    path = fetchgit {
      url = "https://github.com/boostorg/variant?ref=boost-1.89.0";
      rev = "1fd7271d2e34a36f010f8882fdde703ad9a4ffeb";
      hash = "sha256-3Q75TYRc8nrDNg9M+xGK2flEau6xvCsnUYRBo1l0sDw=";
    };
  }
  {
    name = "N-V-__8AAI5fBgALNeyXb0DEVCArdX3aMz4rwz4bZhiQ8Pn4";
    path = fetchgit {
      url = "https://github.com/boostorg/interval?ref=boost-1.89.0";
      rev = "565d0d754f851eb9447745b359ca5be6a033918c";
      hash = "sha256-4neDtrnUcKVhucf3+HvWoEzLA8+vcLgk0cEoVzOCKUc=";
    };
  }
  {
    name = "N-V-__8AAI7OAwBNGHbb3auG83WXxmwyZQOteVESKIeCqVQ3";
    path = fetchgit {
      url = "https://github.com/boostorg/lockfree?ref=boost-1.89.0";
      rev = "4a69f38b3d1d20ac56e60095a550ffb2ce4ccbd7";
      hash = "sha256-0CB1iJcZVpZYni0POMO14kZeODf7sFXp74LMb/5RH2c=";
    };
  }
  {
    name = "N-V-__8AAIGIBQBhI_4SU_mzopfWYmnFFYtDC2YjSCMA3NrO";
    path = fetchgit {
      url = "https://github.com/boostorg/heap?ref=boost-1.89.0";
      rev = "7db5d9db6615b40239a8bb9383a12bd56924bd07";
      hash = "sha256-qz+I1aUSUMD83xHavQK2bbeUAQdNqcz7s58ZzYui7WI=";
    };
  }
  {
    name = "N-V-__8AAIKQDwA0c--Aj6OaH4orOc17CDZKowBOpZoVO1YG";
    path = fetchgit {
      url = "https://github.com/boostorg/function_types?ref=boost-1.89.0";
      rev = "6fba35ace59e9e7b1c3007ca6246a42ed6ead145";
      hash = "sha256-GOyxfIPqyCTHm7Snm0UcTHQaR8bNA5QlNbX+0J1fwSI=";
    };
  }
  {
    name = "N-V-__8AAIV1FwDSpq88-9u5tgH11coxur4KVuaAT4qc_NMJ";
    path = fetchgit {
      url = "https://github.com/boostorg/locale?ref=boost-1.89.0";
      rev = "9b7775715a50e62c5bc0ed99d65e0f56c06361f4";
      hash = "sha256-upelF8VheXf/1JufbNpb/9Pratl6gGXbHwoatJNNJh8=";
    };
  }
  {
    name = "N-V-__8AAI_2DwAAb7VpZLRfaT0nhgf4YaCGGSdiYOL9B7Ch";
    path = fetchgit {
      url = "https://github.com/boostorg/exception?ref=boost-1.89.0";
      rev = "9238ef8e7f97e619ed3e58bc7becf16b4966ccf0";
      hash = "sha256-E38F9Pnj/DK79eTq/kkajQTGwr+94GIYLoiS02I4Qic=";
    };
  }
  {
    name = "N-V-__8AAIbhogBBR0oCd8YkyM92CNRHRssIwCegr2aH_KJ0";
    path = fetchgit {
      url = "https://github.com/boostorg/gil?ref=boost-1.89.0";
      rev = "201f31c76eed54b304f8d89e44da08a5e8825094";
      hash = "sha256-dhb1HDKUmedscO1pEFYQM0h7qZMVAz0I0ARamfWhZnU=";
    };
  }
  {
    name = "N-V-__8AAIg9TQDdQ2vR5IvCCy4llIYMiArhZrT6i7glL-oz";
    path = fetchgit {
      url = "https://github.com/boostorg/hana?ref=boost-1.89.0";
      rev = "bc49ee25638e59d977edff5737b4e6bf12c1e5ea";
      hash = "sha256-lFaH6qPEDtYEKAjZhFyvqtfQR3GENkE/15zkGNgAy7A=";
    };
  }
  {
    name = "N-V-__8AAJ2DBQCKC9z4NhZswoPXswGEttik3uBYBck-CZ2V";
    path = fetchgit {
      url = "https://github.com/boostorg/container_hash?ref=boost-1.89.0";
      rev = "5d8b8ac2b9d9d7cb3818f88fd7e6372e5f072ff5";
      hash = "sha256-Yu3Qc7yRFkusfnS107Rrs+yXFcBQuNhfZ9lAAMsHbLA=";
    };
  }
  {
    name = "N-V-__8AAJAkjwAYYXHVJKUhUMKuToV0TNmsBJD2iHWobxdT";
    path = fetchgit {
      url = "https://github.com/boostorg/beast?ref=boost-1.89.0";
      rev = "9b24b28d502946583300d3e58767cb30a8ec8486";
      hash = "sha256-qSmneJsKc7KkUZldhW0jyUqTb5SzyZhkB9EOaNYtErw=";
    };
  }
  {
    name = "N-V-__8AAJHfAQDwMmkntNc6N5YRCF2WsmHiaO9p1yJr6BJi";
    path = fetchgit {
      url = "https://github.com/boostorg/assert?ref=boost-1.89.0";
      rev = "5dcb2af5213ae132b7531e45e7f93258cc33ffd8";
      hash = "sha256-uTS34jOzHoo4yz1ZcN6gHYYzR7ihcPlvVrmOHnRK8BU=";
    };
  }
  {
    name = "N-V-__8AAJXCBgA7KCqx4FXdE85HRUeu8t97czaLcbgr1HbL";
    path = fetchgit {
      url = "https://github.com/boostorg/compat?ref=boost-1.89.0";
      rev = "e3746402659838fbd5efd91f4110ad0e0c63c957";
      hash = "sha256-CJcRUJHo13JjZTozfoA99kHdS5UPS0gBr0lOqmZ1Lmk=";
    };
  }
  {
    name = "N-V-__8AAJdoWwC2cyp_jJ2plRE9KnBTkdESqTkr4Stcx8gf";
    path = fetchgit {
      url = "https://github.com/boostorg/url?ref=boost-1.89.0";
      rev = "8d5cc6e34884b4f3a8a43c8f9706c0f5800238a0";
      hash = "sha256-l6f+BEnasK3r0K65AHlF6xgOhUEgj/TxUkYEcRu0jAg=";
    };
  }
  {
    name = "N-V-__8AAJmKFwBGnXY8Tntsqzf7D8ZUV1gzARlvkEIG-mzN";
    path = fetchgit {
      url = "https://github.com/boostorg/charconv?ref=boost-1.89.0";
      rev = "728f7c4a85d7893c91c5fd85220367bb17cd06b5";
      hash = "sha256-DmxF/0Ja79+gWxYJvWoMCmBmxoPZyor+nijbuYDnWVk=";
    };
  }
  {
    name = "N-V-__8AAJzPLAAX-jXQUFcp9UoyW-ROazUE4O0rfmkev7SZ";
    path = fetchgit {
      url = "https://github.com/boostorg/iterator?ref=boost-1.89.0";
      rev = "2a0b753691f326154436fa641287e6336c19d80e";
      hash = "sha256-V30bjYRd2/Cyehhyy9g5P99Cz/3I3pvHWe+CPDoHPEU=";
    };
  }
  {
    name = "N-V-__8AAK3NKABu1nbMdl-FFUCozuoyor6g7sC_9ZFBQy9P";
    path = fetchgit {
      url = "https://github.com/boostorg/interprocess?ref=boost-1.89.0";
      rev = "2c3d4f8bb91400298f285ebd197d808cf14b126a";
      hash = "sha256-KvoL+xWUa6uM5NtqILeP3sLHYAErcuzELLOjcxK7xEA=";
    };
  }
  {
    name = "N-V-__8AAK5-OwAjoTGZtX_qcfh6hQDM2cbkRbPXD7fxu8hY";
    path = fetchgit {
      url = "https://github.com/boostorg/ublas?ref=boost-1.89.0";
      rev = "15d871b410ff92592c6f3e0a53550035e7817046";
      hash = "sha256-R4ldmXdoyGHTWFX3Brdru+68ZLefDtDWkOuEJUglEPE=";
    };
  }
  {
    name = "N-V-__8AAK7pAACf3O82lupST65fn7dA4KhONnxefg-gqW0z";
    path = fetchgit {
      url = "https://github.com/boostorg/static_assert?ref=boost-1.89.0";
      rev = "9a6a86efc8dea37083ed1a78fb0998673517cf4e";
      hash = "sha256-eqL5ociucdx7tAxdN2rNY4JtX/vI0e8mOPB50VnLzoA=";
    };
  }
  {
    name = "N-V-__8AAKR6BADavdkISDKa2l67WkyvTn1krdMceO6evWjs";
    path = fetchgit {
      url = "https://github.com/boostorg/concept_check?ref=boost-1.89.0";
      rev = "0ef7f2b5daeaa125a53d98affba8f40091d24b17";
      hash = "sha256-c+EsxJoHN+/kOwKiwsoSIMgza2wA5H3pIcwOu9/mPi4=";
    };
  }
  {
    name = "N-V-__8AAKdJLQG_Htvv2JMcB2rMck3xsHsXXykRgsThNc5r";
    path = fetchgit {
      url = "https://github.com/boostorg/json?ref=boost-1.89.0";
      rev = "3c80c097d2fe2266d3d41f4121d7af24e122e996";
      hash = "sha256-OhXjpqM2dyfQNH2ShPahoM5lAzpZ9sUQMlw/FcuyUiA=";
    };
  }
  {
    name = "N-V-__8AAKzDCAA4mjzbXNbygO1YuX4mU1AtyOWaAwcoX3rx";
    path = fetchgit {
      url = "https://github.com/boostorg/signals2?ref=boost-1.89.0";
      rev = "898c81affdac7759768f846ea461d2364b028f0e";
      hash = "sha256-qB7bUzrd5kdX7/JkLSpgkNATVCjLthkhhTWdq2IZzto=";
    };
  }
  {
    name = "N-V-__8AAL2PJwA7essATOp2Xd8l1jEo8e7fyahbreh2v3mQ";
    path = fetchgit {
      url = "https://github.com/boostorg/compute?ref=boost-1.89.0";
      rev = "cf7907574d6159cd43e6cf687a7b656278c61dd0";
      hash = "sha256-OwoB+PLiDp5QdKy77qDFfBMJ6e8WzLjAC8OBWTiIB+Q=";
    };
  }
  {
    name = "N-V-__8AAL7NHACmKrgvrDf_7aXv_vsiixCWvOv2LHOh4JNk";
    path = fetchgit {
      url = "https://github.com/boostorg/parameter?ref=boost-1.89.0";
      rev = "67861ef6ade2db396af4a3fd9e47647d8b01f73c";
      hash = "sha256-A8qoN392ZhZVj+rIFYai8ODY2r+ZKWKzC8mEcZzgH5k=";
    };
  }
  {
    name = "N-V-__8AALCYJwGwrs7rO_IvByy6Lt9m7O9-bYLL5JxbWw6M";
    path = fetchgit {
      url = "https://github.com/boostorg/phoenix?ref=boost-1.89.0";
      rev = "8913607a3788cb82d48ed461ea59c919b7bad3df";
      hash = "sha256-1PmU/DS4nV1mVvAeWWWlWP5K3aUQV1opasRnoDV0EjI=";
    };
  }
  {
    name = "N-V-__8AALI0tQDZW9UfY8zpFBacRQKLZ19tOAZCL4OAlZtG";
    path = fetchgit {
      url = "https://github.com/boostorg/preprocessor?ref=boost-1.89.0";
      rev = "cd1b1bd03900b68505822cfa25cb16851bd6caf1";
      hash = "sha256-4GTIVg58rx21Sqpj5fQH8VXVdHCGI9reauZ64ZlDhfA=";
    };
  }
  {
    name = "N-V-__8AALKyCwA3vPUL9O__Q4y3m193L6sycgS9J03KBzsm";
    path = fetchgit {
      url = "https://github.com/boostorg/hof?ref=boost-1.89.0";
      rev = "63ac019fca325038bfb4f56db17fbb281d2b5f49";
      hash = "sha256-A/zulgYRaEDVmkcXk9c41vWGi8X6d4RiSFt8WoKS24A=";
    };
  }
  {
    name = "N-V-__8AALNNQQCHJ90BqIiWlYmFjpkaEKejVPYEftqw7gIs";
    path = fetchgit {
      url = "https://github.com/boostorg/safe_numerics?ref=boost-1.89.0";
      rev = "777e0be5ec763d0333a717c5e421a4f7c5e5bdc9";
      hash = "sha256-zBBR8khPkv7TLU+Eb82nexA9ZdB/BPMwiV8GKSl5OO4=";
    };
  }
  {
    name = "N-V-__8AALO0MwBElcnzmpmvZb57SyPoGw_68--ZJx11tj7o";
    path = fetchgit {
      url = "https://github.com/boostorg/wave?ref=boost-1.89.0";
      rev = "d7aa5a369d8f2faf48c8ea16ba041dfabbf91363";
      hash = "sha256-0J83PDzkcp42cUmXytMH6InkZF0SHZDhvbg6n+abD7U=";
    };
  }
  {
    name = "N-V-__8AALTJBwCHHiM6Be55w4Df-SLIOyD0xzirjjR8PIBN";
    path = fetchgit {
      url = "https://github.com/boostorg/multi_array?ref=boost-1.89.0";
      rev = "0c5348bef71b890c4bd06eff1ee5ebda69e7b27a";
      hash = "sha256-KU/f23Tpt2Ckc4ZakwM79i/WNUUZSxm3Al/LTLd/VZo=";
    };
  }
  {
    name = "N-V-__8AALiaAQBkqXkWmZ90CMgy2wbe3pgedtfkFYCsLgto";
    path = fetchgit {
      url = "https://github.com/boostorg/align?ref=boost-1.89.0";
      rev = "5ad7df63cd792fbdb801d600b93cad1a432f0151";
      hash = "sha256-z1HD4rFJczWaFf6s975quZy6thaA3J128N24QJSkZig=";
    };
  }
  {
    name = "N-V-__8AAM3hCgB8Arslq5pHATUljnwANJKh9EMM95ERNJmK";
    path = fetchgit {
      url = "https://github.com/boostorg/predef?ref=boost-1.89.0";
      rev = "e1211a4ca467bb6512e99025772ca25afa8d6159";
      hash = "sha256-QZZJ98YKbmewom2CVBuzw6UZhFChWlQUu/gNvQK39oE=";
    };
  }
  {
    name = "N-V-__8AAM7xDAAh6UgGfBTGzSd5M2Y3EAYXVo_lz03cb4H-";
    path = fetchgit {
      url = "https://github.com/boostorg/utility?ref=boost-1.89.0";
      rev = "211570f2b972f66e368e4fe32b00fee31e597d25";
      hash = "sha256-DzvYhXlq2cQjlrhHT2uwxIa40PzbNLrhDe8LRQEZVxM=";
    };
  }
  {
    name = "N-V-__8AAMDrIwAmho_WzB-7Tt4V7NqUcCSwj0Oda5mjoPWd";
    path = fetchgit {
      url = "https://github.com/boostorg/intrusive?ref=boost-1.89.0";
      rev = "23e7a9cbf54f69f2bdc22951af959af74b037d10";
      hash = "sha256-QNvRXF1f/crrVG26uuHG7nsX5HcFQpR4sPY7CTQmbxk=";
    };
  }
  {
    name = "N-V-__8AAMOOGwBP_hCvwzKYcwNojW9urbnpDTOB9e7CFFTD";
    path = fetchgit {
      url = "https://github.com/boostorg/date_time?ref=boost-1.89.0";
      rev = "85e637cb325208c2af9af791c3a1948b4888c6cd";
      hash = "sha256-bcIdwZKKA7lUaLg1Amb2QgTizmT1JBH26sYZNAbOX/c=";
    };
  }
  {
    name = "N-V-__8AAMQ4CgBbGUjB0KqaRkOJtlQqQfeTuREDWKHGc4Zp";
    path = fetchgit {
      url = "https://github.com/boostorg/property_tree?ref=boost-1.89.0";
      rev = "2669458cebee100bc1f9f4a9d2f0cd95d07740bc";
      hash = "sha256-1OIOkO9Zild0rOEHN0XR3XuoIB7GiVc9AhMtWPfhMiI=";
    };
  }
  {
    name = "N-V-__8AAMa4BwCpVigub7aSIEgUJohLziOJXDmB3igMP7M8";
    path = fetchgit {
      url = "https://github.com/boostorg/callable_traits?ref=boost-1.89.0";
      rev = "2a56a3a2496cdb66496f844db55085dd992d5e49";
      hash = "sha256-XbO+SB5QhKAJigL/SBl9OIIQl49u6pUuqAMguU8SftQ=";
    };
  }
  {
    name = "N-V-__8AAMckMACDAWQbKCN5wEWdCcnf7fLMkfYBB5wySXUB";
    path = fetchgit {
      url = "https://github.com/boostorg/bimap?ref=boost-1.89.0";
      rev = "f64de6d045bf6aa3f39a672604bcccbc97291525";
      hash = "sha256-60hpOz/h7fZx2kqJUY6ewiNfV4gOfaUy7tozIbplPls=";
    };
  }
  {
    name = "N-V-__8AAMjfAQCFd7AbC0oR2nywxgUAoeLd1PnpMKIv7gtL";
    path = fetchgit {
      url = "https://github.com/boostorg/tokenizer?ref=boost-1.89.0";
      rev = "a1207c1a424ee565344fe5ef00605cb93f5210c2";
      hash = "sha256-dZ6x0OijKYaAJvSwqJnhuCSoPiWG8KI9LdEiUb/0CA8=";
    };
  }
  {
    name = "N-V-__8AAMkRGQCRXp9NP8hEMMLkgBB2P43kgCweo_pwE_AP";
    path = fetchgit {
      url = "https://github.com/boostorg/range?ref=boost-1.89.0";
      rev = "24b7c98ca12708549513adc4770a2cf5586168f9";
      hash = "sha256-tIO+oNRFU4kFiCVe92zUiNUPgwGkcJWNa/2iFPnbdxs=";
    };
  }
  {
    name = "N-V-__8AANBKFAAlncl9PmGon5xIp81-MPLLC5nqH3aCeU6W";
    path = fetchgit {
      url = "https://github.com/boostorg/process?ref=boost-1.89.0";
      rev = "5597aa0055b81017f6ea24cb652f07a014b12771";
      hash = "sha256-OAa/wBrXGK64vgRXsAjO+HNuQGzHqFt7M6vmEUc+x7c=";
    };
  }
  {
    name = "N-V-__8AANFqBQDwAVbaLgTb6OO5ZzQLBjMdd1Ysm06CTj2V";
    path = fetchgit {
      url = "https://github.com/boostorg/lexical_cast?ref=boost-1.89.0";
      rev = "5326b49475f27d04e07fda8759211b5d65d07f64";
      hash = "sha256-hYMy4iPGUm5CQEscY7jqkCsECtQc3Zfq6vxNGIyLM00=";
    };
  }
  {
    name = "N-V-__8AANNsIwDsiqCKw5nWGO_Y7tJpXDYvrWeMWnGtwjAf";
    path = fetchgit {
      url = "https://github.com/boostorg/multi_index?ref=boost-1.89.0";
      rev = "3a4ddd9c7ad29032edd6086687136c42d0dfb03f";
      hash = "sha256-4R8oNyoxAzlR9JayhGclUQdr7oIZHC8CDlOrDQ7AAIU=";
    };
  }
  {
    name = "N-V-__8AANSEDwB5vng_bAG7nvSDqM_lbRkAt6N4sbRHmGrW";
    path = fetchgit {
      url = "https://github.com/boostorg/hash2?ref=boost-1.89.0";
      rev = "5cf695e5e2466df247561894b3c15b4394a68486";
      hash = "sha256-7WvV9zbMApgBlcefO13tF1P0UJ3RRZj+Dmr9T9j7KqI=";
    };
  }
  {
    name = "N-V-__8AANlPGwDDXJm-H0ZZPDpBfm9RChfDqOnB-A9fDn_Y";
    path = fetchgit {
      url = "https://github.com/boostorg/atomic?ref=boost-1.89.0";
      rev = "8a6de6d93dbe123134deff264851a18d96063764";
      hash = "sha256-MkmP/I6kaCzrcelmPZytBbEeEz2SEleNVQ0aJ+weBno=";
    };
  }
  {
    name = "N-V-__8AAO2HBAC1TXKtzo65bNT9u1fcVPWy8hJ5bu3NbgbN";
    path = fetchgit {
      url = "https://github.com/boostorg/function?ref=boost-1.89.0";
      rev = "f6b538dbed2e3047dcbd09eb3f5c7f1ffa90d0a9";
      hash = "sha256-ZfEd50J1Lq1W2X90QYLgkudvofmNHlwgVmIgpQWqdtE=";
    };
  }
  {
    name = "N-V-__8AAOCdTABust-DtGP27othQo0yvXts6oXGQHdi4HNr";
    path = fetchgit {
      url = "https://github.com/boostorg/mysql?ref=boost-1.89.0";
      rev = "6a82609638e88bcea2985069dfc356f32a575a55";
      hash = "sha256-uVVRCgsQxfVi+o8ohX09nOwLMhvYy5SPIjxPtNaosEA=";
    };
  }
  {
    name = "N-V-__8AAOFKzgCCDxTT2niHOb7wshEyuiLr57U5WKBz3a0R";
    path = fetchgit {
      url = "https://github.com/boostorg/spirit?ref=boost-1.89.0";
      rev = "08b3d033c92238f3c4f8d78e8b4e5b1d90307389";
      hash = "sha256-+1+TdO+l/2rnFJ3cbB4GOg0j9LiCRG71WjaU8Gta4+Y=";
    };
  }
  {
    name = "N-V-__8AAOGGGACoUxgHAU7MfgR-ahJInnG7rh-DSY1QgUvn";
    path = fetchgit {
      url = "https://github.com/boostorg/random?ref=boost-1.89.0";
      rev = "ce34d1e3685861bca0e5c08f6f0cbe5701aa1266";
      hash = "sha256-XpYeqRZDRD+z4+gEVd+/r/Mm/M1dXZEeSwhgDKT/ew4=";
    };
  }
  {
    name = "N-V-__8AAOM4fACNeZypFqiZCciOJhBPWiRT4ffcpQniLMox";
    path = fetchgit {
      url = "https://github.com/boostorg/unordered?ref=boost-1.89.0";
      rev = "59e2a562edf0759e0ac52f659d25e0907ed7bec6";
      hash = "sha256-0ZjkYdIXD53P0lsln4It0xcjAr5nZCeIFva7tXb66Pg=";
    };
  }
  {
    name = "N-V-__8AAOPNBgANRzjmP1uiGRpxTpUnUwFR3c3PZVUAMP40";
    path = fetchgit {
      url = "https://github.com/boostorg/bloom?ref=boost-1.89.0";
      rev = "42ac5003f8742981a9731ae443a99be6b8fa23bc";
      hash = "sha256-gUNbHOqIv1Rk0SmlC8nXF7fhQhQXiuVOIPbhA4uHQ4I=";
    };
  }
  {
    name = "N-V-__8AAOQD7wC4pEgByUp4TphJvvtm476CD8o8BM14q_T4";
    path = fetchgit {
      url = "https://github.com/boostorg/fusion?ref=boost-1.89.0";
      rev = "53da4e0b2c8cd4969b09fa646d314ac0c414c1ff";
      hash = "sha256-l6Jp4v3AZk5FpogTrOnly3VS+MDdYVi1fAXJiBXp0uA=";
    };
  }
  {
    name = "N-V-__8AAOQpAgDDYwqpKtDmaN6D3mnObQIVMFIYhyhhtsq_";
    path = fetchgit {
      url = "https://github.com/boostorg/any?ref=boost-1.89.0";
      rev = "9b1941c787f2769fcb6afdb0cef621db80f953a6";
      hash = "sha256-eaguueOb6v95vnncZzMAVpFTlY6dy23Lw56ftc8sZLw=";
    };
  }
  {
    name = "N-V-__8AAOZmCADODeMFdbLe1jAS_JVYPMQ3d3Jc3JyfDul9";
    path = fetchgit {
      url = "https://github.com/boostorg/tti?ref=boost-1.89.0";
      rev = "03734c54a51b6372ac3296d2fe5103b7360bcd3f";
      hash = "sha256-PK0OwphyXnWesi9zA1rUSWkQMiO1cq2Th/Ig42PXM0s=";
    };
  }
  {
    name = "N-V-__8AAOwSDwDMj4wdHAD_UtIddVzzdKrSuVY4bhAngr4e";
    path = fetchgit {
      url = "https://github.com/boostorg/mp11?ref=boost-1.89.0";
      rev = "2fb81c24534663a99f9570b99a3c748393a23dba";
      hash = "sha256-K0b8exf6KqrnoiV0Yl3h982gs2AI+OZMCFz/HlEORAk=";
    };
  }
  {
    name = "N-V-__8AAP4lDgBa2x-KENz-ob8HIYVLP3Q637QSoAEf6KJ5";
    path = fetchgit {
      url = "https://github.com/boostorg/mqtt5?ref=boost-1.89.0";
      rev = "620df1f9934925ac6044e4619c701d6dcf9dc8b6";
      hash = "sha256-fnsgGO7TBkw7hF7QtfLnQ7Z2IJfuUAro42lVFC5si4s=";
    };
  }
  {
    name = "N-V-__8AAP5SDQBITJgI5Jcyk3yGlFe0b_TqZIsjDZUydiC6";
    path = fetchgit {
      url = "https://github.com/boostorg/type_erasure?ref=boost-1.89.0";
      rev = "5281f14d3cb59f978c8cb6cbb90ce92dde4e3e13";
      hash = "sha256-XDj8X0A92d3Fy+zCfJl71T2/GNGn4OVDybwx30RJVns=";
    };
  }
  {
    name = "N-V-__8AAP87CACoPesrgVNchRs4kD-neM6sb9cTaXhniOPo";
    path = fetchgit {
      url = "https://github.com/boostorg/circular_buffer?ref=boost-1.89.0";
      rev = "a08a5b55ee82e0c2487523471379ac53a23935dc";
      hash = "sha256-TQL6jE0u5XokXiyzxhphtactqjPPhR29S/ideCy6UaM=";
    };
  }
  {
    name = "N-V-__8AAPedBgE6M27iCELCBd3vV5OJ8UgeUojSrHfGLLEV";
    path = fetchgit {
      url = "https://github.com/boostorg/graph?ref=boost-1.89.0";
      rev = "54a94911e68dccf5812b32d018566566700499f3";
      hash = "sha256-aaO82TtjfQ6khvDKfHFyG50DtSlkNepr2CIqZB9FsXY=";
    };
  }
  {
    name = "N-V-__8AAPno2wCeM0mFzPP8Bip9rmLRU8piEhhGB31f5VJk";
    path = fetchgit {
      url = "https://github.com/boostorg/multiprecision?ref=boost-1.89.0";
      rev = "e0c112538ff1e903594d039f2eb97e0057737e5d";
      hash = "sha256-ni6F9xjW1x1WIfkc9gi6bNWgGHtwzPosqMqgtfvDdEA=";
    };
  }
  {
    name = "boost_libraries-1.89.0-frkKHLCXAQASDNJkyAQCiQZKs1kmnLozkP6Mx46J5d1_";
    path = fetchgit {
      url = "https://github.com/allyourcodebase/boost-libraries-zig";
      rev = "b04c323025691d45ad8e1530c0b523e765a9f643";
      hash = "sha256-sQVCFXs0cQ5NA/wukkMv6tbrbpjdmMMldbtq9o2ieHk=";
    };
  }
  {
    name = "zig_compile_commands-0.0.1-OZg5-ULBAABTh3NXO3WXoSUX1474ez0EouuoT2yDANhz";
    path = fetchzip {
      url = "https://github.com/the-argus/zig-compile-commands/archive/70fb439897e12cae896c071717d7c9c382918689.tar.gz";
      hash = "sha256-dUtfifueNJkwBvbossc7Eohv6QbH+9vzCiMReghOgu8=";
    };
  }
]
