OUTDIR := "./bin"
DOTNET_FLAGS := env('DOTNET_FLAGS',"")
ZIG_FLAGS := env('ZIG_FLAGS',"")

all: install

clean:
  rm -rf ./**/obj/
  rm -rf ./**/bin/
  rm -f ./**/compile_commands.json
  rm -rf ./Native/.zig-cache/
  rm -rf ./Native/zig-out/
  rm -f ./Native/bindings/*.cs
  rm -f ./**/*_wrap.cxx
  rm -f ./**/__*.zig
  dotnet clean

[working-directory: "./Native"]
zon2nix:
  zon2nix > ./build.zig.zon.nix

swig:
  mkdir -p ./Native/bindings/
  rm -f ./Native/bindings/*.cs
  rm -f ./Native/swig_wrap.cxx
  swig -csharp -c++ -outdir ./Native/bindings -namespace Native -v ./Native/swig.i

configure: swig
  rm -f *.sln
  rm -f *.slnx
  dotnet new sln
  dotnet sln add ./**/*.csproj
  dotnet restore

[private]
[working-directory: "./Native"]
build-native: swig
  zig build {{ZIG_FLAGS}} --release=fast --verbose

build: swig build-native
  dotnet build ./RuTakingTooLong/RuTakingTooLong.csproj -c Release {{DOTNET_FLAGS}}

install: configure build
  mkdir -p "{{OUTDIR}}"
  cp ./Native/zig-out/lib/** "{{OUTDIR}}"
  dotnet publish -c Release -o "{{OUTDIR}}" {{DOTNET_FLAGS}} ./RuTakingTooLong/RuTakingTooLong.csproj

run: install

